package com.shivhub.backend.repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.math.BigDecimal;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.shivhub.backend.entity.OfflineBill;
import com.shivhub.backend.enums.PaymentMethod;


/*
 * =========================================================
 * OfflineBillRepository
 * =========================================================
 *
 * Database operations for OfflineBill.
 *
 * Used by Seller / Admin Offline Billing (POS) module.
 *
 * =========================================================
 */

public interface OfflineBillRepository
        extends JpaRepository<OfflineBill, Long> {


    /*
     * =========================================================
     * FIND BY BILL NUMBER
     * =========================================================
     *
     * Example:
     *
     * SH-BILL-20260901-001
     *
     */

    Optional<OfflineBill> findByBillNumber(
            String billNumber
    );

    /** Prevents POS return lookup from exposing a bill owned by another seller. */
    Optional<OfflineBill> findByBillNumberAndSellerId(String billNumber, Long sellerId);


    /*
     * =========================================================
     * CHECK BILL NUMBER
     * =========================================================
     */

    boolean existsByBillNumber(
            String billNumber
    );


    /*
     * =========================================================
     * FIND BILLS BY SELLER
     * =========================================================
     *
     * Shows bills generated by a particular seller/staff.
     *
     */

    List<OfflineBill> findBySellerIdOrderByCreatedAtDesc(
            Long sellerId
    );

    Optional<OfflineBill> findTopBySellerIdAndCustomerMobileOrderByCreatedAtDesc(
            Long sellerId,
            String customerMobile
    );


    /*
     * =========================================================
     * FIND BILLS BY CUSTOMER
     * =========================================================
     *
     * Useful for registered customer's purchase history.
     *
     */

    List<OfflineBill> findByCustomerIdOrderByCreatedAtDesc(
            Long customerId
    );

    List<OfflineBill> findByCustomerMobileOrderByCreatedAtDesc(
            String customerMobile
    );

    List<OfflineBill> findByCustomerEmailOrderByCreatedAtDesc(
            String customerEmail
    );


    /*
     * =========================================================
     * FIND BILLS BY PAYMENT METHOD
     * =========================================================
     *
     * CASH
     * UPI
     * CARD
     * BANK_TRANSFER
     * MIXED
     *
     */

    List<OfflineBill> findByPaymentMethodOrderByCreatedAtDesc(
            PaymentMethod paymentMethod
    );


    /*
     * =========================================================
     * FIND BILLS BETWEEN DATES
     * =========================================================
     *
     * Useful for:
     *
     * Daily Report
     * Monthly Report
     * GST Report
     * Sales Report
     *
     */

    List<OfflineBill> findByCreatedAtBetweenOrderByCreatedAtDesc(
            LocalDateTime start,
            LocalDateTime end
    );


    /*
     * =========================================================
     * FIND SELLER BILLS BETWEEN DATES
     * =========================================================
     *
     * Useful for seller/staff-wise sales reports.
     *
     */

    List<OfflineBill> findBySellerIdAndCreatedAtBetweenOrderByCreatedAtDesc(
            Long sellerId,
            LocalDateTime start,
            LocalDateTime end
    );


    /*
     * =========================================================
     * COUNT SELLER BILLS
     * =========================================================
     */

    long countBySellerId(
            Long sellerId
    );


    /*
     * =========================================================
     * COUNT CUSTOMER BILLS
     * =========================================================
     */

    long countByCustomerId(
            Long customerId
    );


    /*
     * =========================================================
     * COUNT BILLS BY PAYMENT METHOD
     * =========================================================
     */

    long countByPaymentMethod(
            PaymentMethod paymentMethod
    );


    /* Aggregate at database level: a dashboard must stay fast even with many bills. */
    @Query("""
            select coalesce(sum(bill.grandTotal), 0)
            from OfflineBill bill
            where bill.sellerId = :sellerId
              and bill.createdAt between :start and :end
            """)
    BigDecimal sumSellerSalesBetween(
            @Param("sellerId") Long sellerId,
            @Param("start") LocalDateTime start,
            @Param("end") LocalDateTime end
    );

    long countBySellerIdAndCreatedAtBetween(
            Long sellerId,
            LocalDateTime start,
            LocalDateTime end
    );
}
