import { Link, useLocation } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";
import { AtSign, BookOpen, Box, Building2, Camera, ChevronDown, CircleHelp, FileText, Globe2, Handshake, Headphones, HeartHandshake, Laptop, MessageCircle, PackageCheck, Play, Recycle, ShieldCheck, ShoppingBag, Smartphone, Store, Truck, Tv, UserRound, Users, WalletCards } from "lucide-react";
import { websiteContentApi } from "../services/websiteContentApi";
import "./SiteFooter.css";

const socialFields = [["instagramUrl", "Instagram", Camera], ["facebookUrl", "Facebook", Users], ["youtubeUrl", "YouTube", Play], ["whatsappUrl", "WhatsApp", MessageCircle], ["websiteUrl", "Website", Globe2]];
const emptySettings = { brandName: "ShivHub", legalBusinessName: "", supportEmail: "", supportPhone: "", businessAddress: "", supportHours: "", enabledPaymentMethods: "" };
const productPath = category => `/customer/products${category ? `?category=${encodeURIComponent(category)}` : ""}`;

export default function SiteFooter() {
    const location = useLocation();
    const [settings, setSettings] = useState(emptySettings);
    const [openGroups, setOpenGroups] = useState({ brand: true });
    useEffect(() => { let active = true; websiteContentApi.getSettings().then(data => { if (active && data) setSettings(value => ({ ...value, ...data })); }).catch(() => {}); return () => { active = false; }; }, []);
    const isSeller = location.pathname.startsWith("/seller");
    const socials = socialFields.filter(([key]) => settings[key]);
    const paymentMethods = String(settings.enabledPaymentMethods || "").split(",").map(value => value.trim()).filter(Boolean);
    const groups = useMemo(() => [
        { id: "brand", title: settings.brandName, Icon: ShoppingBag, content: <><p className="footer-description">{settings.businessAddress ? "A trusted marketplace with customer support and verified business details." : "Explore products, trusted seller fulfilment and ShivHub customer support."}</p><div className="footer-values"><span><ShieldCheck size={18} />Genuine products</span><span><Store size={18} />Trusted sellers</span><span><Truck size={18} />Delivery support</span><span><Headphones size={18} />Dedicated help</span></div>{settings.supportEmail && <a href={`mailto:${settings.supportEmail}`}><AtSign size={15} />{settings.supportEmail}</a>}{settings.supportPhone && <a href={`tel:${settings.supportPhone.replace(/\s/g, "")}`}><Headphones size={15} />{settings.supportPhone}</a>}</> },
        { id: "shop", title: "Shop", Icon: Store, content: <><Link to={productPath("Mobiles")}><Smartphone size={15} />Mobiles</Link><Link to={productPath("Laptops")}><Laptop size={15} />Laptops</Link><Link to={productPath("Televisions")}><Tv size={15} />TV & Electronics</Link><Link to={productPath("Accessories")}><PackageCheck size={15} />Accessories</Link><Link to="/customer/second-hand-market"><Recycle size={15} />Second-hand market</Link><Link to={productPath()}><ShoppingBag size={15} />All categories</Link></> },
        { id: "help", title: "Customer Help", Icon: Headphones, content: <><Link to="/contact"><MessageCircle size={15} />Contact us</Link><Link to="/help"><CircleHelp size={15} />Help / FAQ</Link><Link to="/customer/orders"><Truck size={15} />Track order</Link><Link to="/warranty-policy"><ShieldCheck size={15} />Warranty support</Link><Link to="/return-replacement"><Recycle size={15} />Return & replacement</Link><Link to="/grievance"><HeartHandshake size={15} />Complaints</Link></> },
        { id: "policies", title: "Policies", Icon: FileText, content: <><Link to="/terms"><FileText size={15} />Terms & conditions</Link><Link to="/privacy-policy"><ShieldCheck size={15} />Privacy policy</Link><Link to="/cancellation-refund"><Recycle size={15} />Cancellation & refund</Link><Link to="/shipping-policy"><Truck size={15} />Shipping & delivery</Link><Link to="/payment-security"><WalletCards size={15} />Payment security</Link><Link to="/cookie-policy"><BookOpen size={15} />Cookie policy</Link></> },
        { id: "sell", title: "Sell With Us", Icon: Building2, content: <><Link to="/register"><Store size={15} />Become a seller</Link><Link to="/login"><UserRound size={15} />Seller login</Link><Link to="/seller-terms"><FileText size={15} />Seller terms</Link><Link to="/seller-support"><Headphones size={15} />Seller support</Link><Link to="/partner-program"><Handshake size={15} />Partner program</Link><Link to="/api-integration"><Box size={15} />API / integration</Link></> }
    ], [settings]);
    if (location.pathname.startsWith("/admin")) return null;
    if (isSeller) return <footer className="site-footer seller"><div><strong>{settings.brandName}</strong><span>Platform policy and support links for sellers.</span></div><nav><Link to="/seller-terms">Seller terms</Link><Link to="/seller-support">Support</Link><Link to="/contact">Contact</Link></nav></footer>;
    return <footer className="site-footer">
        <span className="footer-ambient footer-ambient-blue" aria-hidden="true" /><span className="footer-ambient footer-ambient-orange" aria-hidden="true" />
        <section className="footer-assurance" aria-label="ShivHub assurances"><article><Truck aria-hidden="true" /><span><strong>Delivery support</strong><small>Availability confirmed at checkout</small></span></article><article><ShieldCheck aria-hidden="true" /><span><strong>Secure payments</strong><small>Protected payment processing</small></span></article><article><Recycle aria-hidden="true" /><span><strong>Returns &amp; refunds</strong><small>According to the product policy</small></span></article><article><Headphones aria-hidden="true" /><span><strong>Customer support</strong><small>{settings.supportHours || "Support details set by admin"}</small></span></article></section>
        <section className="footer-grid">{groups.map(group => <article className={`footer-group ${openGroups[group.id] ? "open" : ""}`} key={group.id}><button type="button" onClick={() => setOpenGroups(value => ({ ...value, [group.id]: !value[group.id] }))} aria-expanded={!!openGroups[group.id]}><span className="footer-heading"><group.Icon size={20} aria-hidden="true" /><h3>{group.title}</h3></span><ChevronDown className="footer-chevron" size={18} aria-hidden="true" /></button><div className="footer-group-content">{group.content}</div></article>)}</section>
        <section className="footer-utility"><div className="footer-app"><Smartphone size={30} aria-hidden="true" /><span><strong>Shop ShivHub</strong><small>Access your account from any device.</small></span></div><div className="footer-payments"><strong><WalletCards size={18} /> Available payment methods</strong><div>{paymentMethods.length ? paymentMethods.map(method => <span key={method} className="pay-chip">{method}</span>) : <span className="footer-pending">Payment methods are configured by admin.</span>}</div></div><div className="footer-follow"><strong>Follow us</strong><div>{socials.map(([key, label, Icon]) => <a key={key} href={settings[key]} target="_blank" rel="noopener noreferrer" aria-label={`Follow ${settings.brandName} on ${label}`} title={`Follow on ${label}`}><Icon size={19} aria-hidden="true" /></a>)}</div></div></section>
        <section className="footer-bottom"><span>© {new Date().getFullYear()} {settings.legalBusinessName || settings.brandName}. All rights reserved.</span><nav><Link to="/about">About</Link><Link to="/careers">Careers</Link><Link to="/sitemap">Sitemap</Link><Link to="/contact">Contact</Link></nav></section>
    </footer>;
}
