import { useEffect, useState } from "react";
import SellerSidebar from "./SellerSidebar";
import api from "../../services/api";
import { getPurchases } from "../../services/purchaseService";
import "./PaymentModule.css";
import "./PremiumPolish.css";

const money = value => `₹${Number(value || 0).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
export default function DistributorCreditNotesModule() {
    const [purchases, setPurchases] = useState([]), [notes, setNotes] = useState([]), [error, setError] = useState(""), [search, setSearch] = useState("");
    const [form, setForm] = useState({ purchaseId: "", creditNoteNumber: "", amount: "", creditNoteDate: new Date().toISOString().slice(0, 10), reason: "", remarks: "" });
    const load = async () => { try { const [purchaseData, noteData] = await Promise.all([getPurchases(), api.get("/api/distributor-credit-notes")]); setPurchases(purchaseData || []); setNotes(noteData.data || []); } catch (err) { setError(err.response?.data?.message || "Unable to load credit notes."); } };
    useEffect(() => { void load(); }, []);
    const save = async event => { event.preventDefault(); try { await api.post("/api/distributor-credit-notes", { ...form, purchaseId: Number(form.purchaseId), amount: Number(form.amount) }); setForm({ purchaseId: "", creditNoteNumber: "", amount: "", creditNoteDate: new Date().toISOString().slice(0, 10), reason: "", remarks: "" }); await load(); } catch (err) { setError(err.response?.data?.message || "Credit note could not be saved."); } };
    const filteredNotes = notes.filter(note => !search || [note.creditNoteNumber, note.purchaseInvoiceNumber, note.reason, note.amount].some(value => String(value || "").toLowerCase().includes(search.toLowerCase())));
    return <div className="payment-page"><SellerSidebar/><main className="payment-main"><header><div><span>PURCHASE ADJUSTMENTS</span><h1>Distributor Credit Notes</h1><p>CN is always linked to the original distributor bill and reduces its payable amount.</p></div><button onClick={load}>Refresh</button></header>{error && <div className="payment-error">{error}</div>}<section className="payment-entry"><form onSubmit={save}><h2>Add Credit Note</h2><select required value={form.purchaseId} onChange={e => setForm({ ...form, purchaseId: e.target.value })}><option value="">Select original purchase bill</option>{purchases.map(p => <option key={p.id} value={p.id}>{p.invoiceNumber} — {p.distributor?.distributor?.businessName || "Distributor"} — {money(p.grandTotal)}</option>)}</select><input required placeholder="Credit note number" value={form.creditNoteNumber} onChange={e => setForm({ ...form, creditNoteNumber: e.target.value })}/><input required type="number" min="0.01" placeholder="CN amount" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })}/><input type="date" value={form.creditNoteDate} onChange={e => setForm({ ...form, creditNoteDate: e.target.value })}/><input placeholder="Reason" value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })}/><input placeholder="Remarks" value={form.remarks} onChange={e => setForm({ ...form, remarks: e.target.value })}/><button>Save CN</button></form></section><section className="payment-filter"><input placeholder="Search CN number, original bill, reason or amount" value={search} onChange={e => setSearch(e.target.value)}/></section><section className="payment-table"><table><thead><tr><th>CN Number</th><th>Original Bill</th><th>Date</th><th>CN Amount</th><th>Reason</th></tr></thead><tbody>{filteredNotes.map(note => <tr key={note.id}><td><b>{note.creditNoteNumber}</b></td><td>{note.purchaseInvoiceNumber}</td><td>{note.creditNoteDate}</td><td>{money(note.amount)}</td><td>{note.reason || "—"}</td></tr>)}</tbody></table></section></main></div>;
}
