import { useEffect, useMemo, useState } from "react";
import api from "../../services/api";
import SellerSidebar from "./SellerSidebar";
import "./SellerDataModule.css";
import "./SellerBusinessModules.css";
import "./PremiumPolish.css";
const today = () => new Date().toISOString().slice(0,10);
const empty = () => ({ category:"RENT", description:"", amount:"", expenseDate:today(), paymentMethod:"CASH", notes:"" });
export default function Expenses(){const [items,setItems]=useState([]),[form,setForm]=useState(empty()),[error,setError]=useState(""),[saving,setSaving]=useState(false);const load=()=>api.get("/api/seller/expenses").then(r=>setItems(Array.isArray(r.data)?r.data:[])).catch(err=>setError(err.response?.data?.message||"Could not load expenses."));useEffect(()=>{void load();},[]);const total=useMemo(()=>items.reduce((sum,x)=>sum+Number(x.amount||0),0),[items]);const submit=async e=>{e.preventDefault();try{setSaving(true);await api.post("/api/seller/expenses",{...form,amount:Number(form.amount)});setForm(empty());void load();}catch(err){setError(err.response?.data?.message||"Could not save expense.");}finally{setSaving(false);}};return <div className="seller-data-page"><SellerSidebar/><main className="seller-data-main"><header><span>EXPENSES</span><h1>Shop expenses</h1><p>Track rent, salary, utilities and daily operational spending.</p></header>{error&&<div className="seller-data-error">{error}</div>}<section className="seller-data-card"><h2>Add expense</h2><form className="seller-data-form" onSubmit={submit}><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["RENT","SALARY","ELECTRICITY","INTERNET","TRANSPORT","MARKETING","MAINTENANCE","OTHER"].map(x=><option key={x}>{x}</option>)}</select></label><label>Description<input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Amount<input required type="number" min="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Date<input required type="date" value={form.expenseDate} onChange={e=>setForm({...form,expenseDate:e.target.value})}/></label><label>Payment<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}>{["CASH","UPI","CARD","BANK_TRANSFER"].map(x=><option key={x}>{x}</option>)}</select></label><button disabled={saving}>{saving?"Saving…":"Add expense"}</button></form></section><section className="seller-data-card"><h2>This period: ₹{total.toLocaleString("en-IN",{minimumFractionDigits:2})}</h2><table><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Payment</th><th>Amount</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.expenseDate}</td><td>{x.category}</td><td>{x.description}</td><td>{x.paymentMethod||"—"}</td><td>₹{Number(x.amount).toFixed(2)}</td></tr>)}</tbody></table></section></main></div>}
