import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import SellerSidebar from "./SellerSidebar";
import { afterSalesService } from "../../services/afterSalesService";
import "./SellerOfflineReturns.css";

const REASONS = ["DEFECTIVE", "DAMAGED_ON_DELIVERY", "WRONG_PRODUCT", "MISSING_ACCESSORY", "NOT_AS_DESCRIBED", "DOA", "OTHER"];
const showSerial = serial => [serial.imei1 && `IMEI 1: ${serial.imei1}`, serial.imei2 && `IMEI 2: ${serial.imei2}`, serial.serialNumber && `Serial: ${serial.serialNumber}`].filter(Boolean).join(" · ");

export default function SellerOfflineReturns() {
    const navigate = useNavigate();
    const [billNumber, setBillNumber] = useState(""); const [bill, setBill] = useState(null); const [itemId, setItemId] = useState(""); const [serialId, setSerialId] = useState("");
    const [reason, setReason] = useState("DEFECTIVE"); const [issue, setIssue] = useState(""); const [condition, setCondition] = useState("");
    const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
    const selectedItem = useMemo(() => bill?.items?.find(item => String(item.billItemId) === String(itemId)) || null, [bill, itemId]);

    const lookup = async event => { event.preventDefault(); if (!billNumber.trim()) return; setLoading(true); setError(""); setNotice(""); setBill(null); setItemId(""); setSerialId(""); try { const response = await afterSalesService.sellerOfflineReturnLookup(billNumber.trim()); setBill(response.data); } catch (requestError) { setError(requestError.response?.data?.message || "No eligible bill or exact IMEI/serial was found in your shop."); } finally { setLoading(false); } };
    const selectItem = value => { setItemId(value); const item = bill?.items?.find(row => String(row.billItemId) === String(value)); setSerialId(item?.serials?.length === 1 ? String(item.serials[0].purchaseSerialId) : ""); };
    const createReturn = async event => { event.preventDefault(); if (!bill || !selectedItem) return; setSaving(true); setError(""); setNotice(""); try { const response = await afterSalesService.createSellerOfflineReturn({ offlineBillId: bill.billId, offlineBillItemId: selectedItem.billItemId, purchaseSerialId: serialId ? Number(serialId) : null, returnReason: reason, customerIssue: issue, receivingCondition: condition }); setNotice(`Return intake ${response.data.requestNumber} created. The unit is RETURN_PENDING and cannot be sold until inspection/refund is completed.`); setBill(null); setItemId(""); setSerialId(""); setIssue(""); setCondition(""); } catch (requestError) { setError(requestError.response?.data?.message || "Return intake could not be created."); } finally { setSaving(false); } };

    return <div className="seller-return-page"><SellerSidebar /><main className="seller-return-main"><header><div><p>OFFLINE BILLING · RETURNS</p><h1>Receive customer return</h1><span>Search a paid bill from your own shop. A returned mobile is placed in <strong>RETURN_PENDING</strong> and is never added back to sellable stock automatically.</span></div><button type="button" onClick={() => navigate("/seller/after-sales")}>After-Sales queue</button></header>
        {error && <p className="seller-return-alert error">{error}</p>}{notice && <p className="seller-return-alert success">{notice}</p>}
        <section className="seller-return-card"><form className="seller-return-search" onSubmit={lookup}><label>Original bill number<input value={billNumber} onChange={event => setBillNumber(event.target.value)} placeholder="Example: SH-BILL-20260901-001" required /></label><button disabled={loading}>{loading ? "Searching…" : "Find bill"}</button></form></section>
        {bill && <><section className="seller-return-card seller-return-bill"><div><span>Bill</span><strong>{bill.billNumber}</strong></div><div><span>Customer</span><strong>{bill.customerName || "Walk-in customer"}</strong><small>{bill.customerMobile || "No mobile recorded"}</small></div><div><span>Payment</span><strong>{bill.paymentStatus}</strong></div><div><span>Sale date</span><strong>{bill.saleDate ? new Date(bill.saleDate).toLocaleDateString("en-IN") : "-"}</strong></div></section><section className="seller-return-card"><h2>Select product received from customer</h2><div className="seller-return-items">{bill.items?.map(item => <button type="button" key={item.billItemId} className={`seller-return-item ${String(itemId) === String(item.billItemId) ? "selected" : ""}`} disabled={!item.returnEligible} onClick={() => selectItem(item.billItemId)}><strong>{item.productName}</strong><span>Qty {item.quantity} · Refundable ₹{item.refundableAmount}</span><small>{item.returnEligible ? "Eligible for return intake" : item.ineligibleReason || "Not eligible"}</small></button>)}</div></section>
        {selectedItem && <form className="seller-return-card seller-return-form" onSubmit={createReturn}><h2>Return intake: {selectedItem.productName}</h2>{selectedItem.serials?.length > 0 && <label>Returned IMEI / serial<select value={serialId} onChange={event => setSerialId(event.target.value)} required><option value="">Select physical unit</option>{selectedItem.serials.map(serial => <option value={serial.purchaseSerialId} key={serial.purchaseSerialId}>{showSerial(serial)}</option>)}</select></label>}<label>Return reason<select value={reason} onChange={event => setReason(event.target.value)}>{REASONS.map(value => <option value={value} key={value}>{value.replaceAll("_", " ")}</option>)}</select></label><label>Customer's stated issue<textarea value={issue} onChange={event => setIssue(event.target.value)} minLength="5" maxLength="5000" required placeholder="Record the return reason exactly as explained by the customer" /></label><label>Receiving condition<textarea value={condition} onChange={event => setCondition(event.target.value)} minLength="5" maxLength="5000" required placeholder="Condition at handover: box, accessories, scratches, IMEI, seal, damage" /></label><p className="seller-return-warning">This creates a return case only. Inspect it in After-Sales, approve it, then initiate and complete the verified refund. Do not put the item back into available stock before inspection.</p><button disabled={saving}>{saving ? "Creating return…" : "Receive and create return intake"}</button></form>}</>}
    </main></div>;
}
