package com.shivhub.backend.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import com.shivhub.backend.enums.PaymentMethod;
import com.shivhub.backend.enums.PaymentStatus;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


/*
 * =========================================================
 * OfflineBill
 * =========================================================
 *
 * Represents a bill generated by Seller/Admin at the
 * physical shop counter.
 *
 * This is separate from the online Order entity.
 *
 * Flow:
 *
 * Seller
 *    ↓
 * Offline POS
 *    ↓
 * OfflineBill
 *    ↓
 * Invoice
 *    ↓
 * Stock Reduction
 *
 * =========================================================
 */

@Entity
@Table(name = "offline_bills")

@Data
@NoArgsConstructor
@AllArgsConstructor

public class OfflineBill {
    @Column(name="finance_provider_name",length=150)
    private String financeProviderName;


    /*
     * =========================================================
     * PRIMARY KEY
     * =========================================================
     */

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    /*
     * =========================================================
     * BILL NUMBER
     * =========================================================
     *
     * Customer-facing bill number.
     *
     * Example:
     *
     * SH-BILL-20260901-001
     *
     */

    @Column(
            name = "bill_number",
            nullable = false,
            unique = true
    )
    private String billNumber;


    /*
     * =========================================================
     * SELLER / STAFF ID
     * =========================================================
     *
     * Stores the user who generated the bill.
     *
     * This allows Admin to know:
     *
     * "Who created this bill?"
     *
     */

    @Column(
            name = "seller_id",
            nullable = false
    )
    private Long sellerId;


    /*
     * =========================================================
     * SELLER NAME SNAPSHOT
     * =========================================================
     *
     * We store the name at billing time.
     *
     * If staff name changes later, old invoice still
     * shows the original seller name.
     *
     */

    @Column(
            name = "seller_name"
    )
    private String sellerName;

    /* Salesperson snapshot: historic staff attribution never changes. */
    @Column(name = "sales_person_id")
    private Long salesPersonId;

    @Column(name = "sales_person_name")
    private String salesPersonName;

    /* Seller shop details are snapshotted so a historic invoice never changes. */
    @Column(name = "seller_business_name")
    private String sellerBusinessName;

    @Column(name = "seller_gstin", length = 15)
    private String sellerGstin;

    @Column(name = "seller_business_address", columnDefinition = "TEXT")
    private String sellerBusinessAddress;

    @Column(name = "seller_mobile")
    private String sellerMobile;

    @Column(name = "seller_website_url", length = 2000)
    private String sellerWebsiteUrl;

    @Column(name = "seller_instagram_url", length = 2000)
    private String sellerInstagramUrl;

    @Column(name = "seller_facebook_url", length = 2000)
    private String sellerFacebookUrl;

    @Column(name = "seller_whatsapp_url", length = 2000)
    private String sellerWhatsappUrl;

    @Column(name = "seller_youtube_url", length = 2000)
    private String sellerYoutubeUrl;

    @Column(name = "seller_invoice_terms", columnDefinition = "TEXT")
    private String sellerInvoiceTerms;
    @Column(name = "warranty_period", length = 100) private String warrantyPeriod;
    @Column(name = "warranty_type", length = 50) private String warrantyType;
    @Column(name = "return_policy", columnDefinition = "TEXT") private String returnPolicy;
    @Column(name = "replacement_policy", columnDefinition = "TEXT") private String replacementPolicy;
    @Column(name = "exchange_policy", columnDefinition = "TEXT") private String exchangePolicy;
    @Column(name = "refund_policy", columnDefinition = "TEXT") private String refundPolicy;
    @Column(name = "warranty_terms", columnDefinition = "TEXT") private String warrantyTerms;

    @Column(nullable = false) private boolean invoiceShowAddress = true;
    @Column(nullable = false) private boolean invoiceShowMobile = true;
    @Column(nullable = false) private boolean invoiceShowGstin = true;
    @Column(nullable = false) private boolean invoiceShowCustomerDetails = true;
    @Column(nullable = false) private boolean invoiceShowNotes = true;
    @Column(nullable = false) private boolean invoiceShowWebsite = true;
    @Column(nullable = false) private boolean invoiceShowSocialLinks = false;


    /*
     * =========================================================
     * CUSTOMER ID
     * =========================================================
     *
     * Existing registered customer.
     *
     * NULL is allowed because a walk-in customer may not
     * have an account.
     *
     */

    @Column(
            name = "customer_id"
    )
    private Long customerId;

    /** Additive canonical POS-customer link; legacy customer_id remains unchanged for online accounts. */
    @Column(name = "customer_profile_id")
    private Long customerProfileId;


    /*
     * =========================================================
     * CUSTOMER NAME
     * =========================================================
     *
     * Snapshot of customer name at billing time.
     *
     */

    @Column(
            name = "customer_name",
            nullable = false
    )
    private String customerName;


    /*
     * =========================================================
     * CUSTOMER MOBILE
     * =========================================================
     *
     * Useful for:
     *
     * 1. Invoice
     * 2. WhatsApp
     * 3. Customer history
     *
     */

    @Column(
            name = "customer_mobile"
    )
    private String customerMobile;

    /** Snapshot of the customer's counter consent at the time this bill was created. */
    @Column(name = "whatsapp_consent", nullable = false)
    private boolean whatsappConsent;


    /*
     * =========================================================
     * CUSTOMER EMAIL
     * =========================================================
     *
     * Optional.
     *
     */

    @Column(
            name = "customer_email"
    )
    private String customerEmail;

    @Column(name = "customer_address", columnDefinition = "TEXT")
    private String customerAddress;


    /*
     * =========================================================
     * CUSTOMER GSTIN
     * =========================================================
     *
     * Optional for GST customer billing.
     *
     */

    @Column(
            name = "customer_gstin"
    )
    private String customerGstin;

    /** Optional B2B invoice identity snapshots.  They are nullable for every
     * historical/walk-in bill and are intentionally not copied back to a customer. */
    @Column(name = "customer_legal_name", length = 180)
    private String customerLegalName;

    @Column(name = "customer_trade_name", length = 180)
    private String customerTradeName;

    @Column(name = "place_of_supply", length = 80)
    private String placeOfSupply;

    @Column(name = "customer_tax_type", length = 8)
    private String customerTaxType = "B2C";


    /*
     * =========================================================
     * SUBTOTAL
     * =========================================================
     *
     * Total product amount before discount and tax.
     *
     */

    @Column(
            name = "subtotal",
            precision = 12,
            scale = 2,
            nullable = false
    )
    private BigDecimal subtotal = BigDecimal.ZERO;


    /*
     * =========================================================
     * DISCOUNT
     * =========================================================
     *
     * Total discount applied to this bill.
     *
     */

    @Column(
            name = "discount",
            precision = 12,
            scale = 2,
            nullable = false
    )
    private BigDecimal discount = BigDecimal.ZERO;


    /*
     * =========================================================
     * TAXABLE AMOUNT
     * =========================================================
     *
     * Amount on which GST is calculated.
     *
     */

    @Column(
            name = "taxable_amount",
            precision = 12,
            scale = 2,
            nullable = false
    )
    private BigDecimal taxableAmount = BigDecimal.ZERO;


    /*
     * =========================================================
     * CGST
     * =========================================================
     */

    @Column(
            name = "cgst",
            precision = 12,
            scale = 2,
            nullable = false
    )
    private BigDecimal cgst = BigDecimal.ZERO;


    /*
     * =========================================================
     * SGST
     * =========================================================
     */

    @Column(
            name = "sgst",
            precision = 12,
            scale = 2,
            nullable = false
    )
    private BigDecimal sgst = BigDecimal.ZERO;


    /*
     * =========================================================
     * IGST
     * =========================================================
     *
     * Kept for future inter-state billing.
     *
     */

    @Column(
            name = "igst",
            precision = 12,
            scale = 2,
            nullable = false
    )
    private BigDecimal igst = BigDecimal.ZERO;


    /*
     * =========================================================
     * DELIVERY CHARGE
     * =========================================================
     *
     * Usually zero for physical shop billing.
     *
     * Kept for flexibility.
     *
     */

    @Column(
            name = "delivery_charge",
            precision = 12,
            scale = 2,
            nullable = false
    )
    private BigDecimal deliveryCharge = BigDecimal.ZERO;


    /*
     * =========================================================
     * GRAND TOTAL
     * =========================================================
     */

    @Column(
            name = "grand_total",
            precision = 12,
            scale = 2,
            nullable = false
    )
    private BigDecimal grandTotal = BigDecimal.ZERO;

    /** Loyalty redemption is stored separately so tax and ordinary discounts remain auditable. */
    @Column(name = "loyalty_points_redeemed", nullable = false)
    private Integer loyaltyPointsRedeemed = 0;

    @Column(name = "loyalty_discount", precision = 12, scale = 2, nullable = false)
    private BigDecimal loyaltyDiscount = BigDecimal.ZERO;


    /*
     * =========================================================
     * PAYMENT METHOD
     * =========================================================
     *
     * CASH
     * UPI
     * CARD
     * BANK_TRANSFER
     * MIXED
     *
     */

    @Enumerated(EnumType.STRING)
    @Column(
            name = "payment_method",
            nullable = false,
            length = 40,
            columnDefinition = "varchar(40)"
    )
    private PaymentMethod paymentMethod;

    /* The bill status is derived from verified payment transactions. */
    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status", length = 30)
    private PaymentStatus paymentStatus = PaymentStatus.PENDING;

    /**
     * Razorpay POS bills hold inventory until their server-verified payment is
     * complete. Existing cash/manual bills continue using their current
     * immediate-sale behaviour.
     */
    @Column(name = "inventory_pending")
    private Boolean inventoryPending = false;

    @Column(name = "stock_finalized_at")
    private LocalDateTime stockFinalizedAt;


    /*
     * =========================================================
     * PAYMENT AMOUNT
     * =========================================================
     *
     * Amount received from customer.
     *
     */

    @Column(
            name = "payment_amount",
            precision = 12,
            scale = 2,
            nullable = false
    )
    private BigDecimal paymentAmount = BigDecimal.ZERO;


    /*
     * =========================================================
     * PAYMENT TRANSACTION ID
     * =========================================================
     *
     * Useful for:
     *
     * UPI
     * Card
     * Bank Transfer
     *
     * Optional for Cash.
     *
     */

    @Column(
            name = "transaction_id"
    )
    private String transactionId;


    /*
     * =========================================================
     * NOTES
     * =========================================================
     *
     * Optional billing notes.
     *
     */

    @Column(
            name = "notes",
            columnDefinition = "TEXT"
    )
    private String notes;


    /*
     * =========================================================
     * BILL ITEMS
     * =========================================================
     *
     * One bill can contain many products.
     *
     */

    @OneToMany(
            mappedBy = "offlineBill",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<OfflineBillItem> items =
            new ArrayList<>();


    /*
     * =========================================================
     * CREATED AT
     * =========================================================
     */

    @Column(
            name = "created_at",
            nullable = false,
            updatable = false
    )
    private LocalDateTime createdAt;


    /*
     * =========================================================
     * UPDATED AT
     * =========================================================
     */

    @Column(
            name = "updated_at"
    )
    private LocalDateTime updatedAt;


    /*
     * =========================================================
     * PRE-PERSIST
     * =========================================================
     */

    @PrePersist
    protected void onCreate() {

        LocalDateTime now =
                LocalDateTime.now();

        createdAt = now;
        updatedAt = now;

        if (subtotal == null) {
            subtotal = BigDecimal.ZERO;
        }

        if (discount == null) {
            discount = BigDecimal.ZERO;
        }

        if (taxableAmount == null) {
            taxableAmount = BigDecimal.ZERO;
        }

        if (cgst == null) {
            cgst = BigDecimal.ZERO;
        }

        if (sgst == null) {
            sgst = BigDecimal.ZERO;
        }

        if (igst == null) {
            igst = BigDecimal.ZERO;
        }

        if (deliveryCharge == null) {
            deliveryCharge = BigDecimal.ZERO;
        }

        if (grandTotal == null) {
            grandTotal = BigDecimal.ZERO;
        }

        if (paymentAmount == null) {
            paymentAmount = BigDecimal.ZERO;
        }
    }


    /*
     * =========================================================
     * PRE-UPDATE
     * =========================================================
     */

    @PreUpdate
    protected void onUpdate() {

        updatedAt =
                LocalDateTime.now();
    }


    /*
     * =========================================================
     * ADD ITEM
     * =========================================================
     */

    public void addItem(
            OfflineBillItem item) {

        items.add(item);

        item.setOfflineBill(this);
    }


    /*
     * =========================================================
     * REMOVE ITEM
     * =========================================================
     */

    public void removeItem(
            OfflineBillItem item) {

        items.remove(item);

        item.setOfflineBill(null);
    }
}
