package com.shivhub.backend.controller;
import java.math.BigDecimal; import java.util.*; import org.springframework.data.domain.Page; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import com.shivhub.backend.dto.*; import com.shivhub.backend.entity.*; import com.shivhub.backend.enums.*; import com.shivhub.backend.service.MarketplaceService; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor;

@RestController @RequestMapping("/api/marketplace") @RequiredArgsConstructor
public class MarketplaceController {
 private final MarketplaceService service;
 @GetMapping("/categories") public List<MarketplaceCategory> categories(){return service.publicCategories();}
 @GetMapping("/categories/{id}/subcategories") public List<MarketplaceSubcategory> subcategories(@PathVariable Long id){return service.subcategories(id);}
 @GetMapping("/subcategories/{id}/fields") public List<MarketplaceAttributeDefinition> fields(@PathVariable Long id){return service.fields(id);}
 @GetMapping("/listings") public Page<MarketplaceListingResponse> listings(@RequestParam(defaultValue="") String q,@RequestParam(required=false) Long categoryId,@RequestParam(required=false) Long subcategoryId,@RequestParam(required=false) String condition,@RequestParam(required=false) String city,@RequestParam(required=false) BigDecimal minPrice,@RequestParam(required=false) BigDecimal maxPrice,@RequestParam(defaultValue="0") int page){return service.search(q,categoryId,subcategoryId,condition,city,minPrice,maxPrice,page);}
 @GetMapping("/listings/{id}") public MarketplaceListingResponse detail(@PathVariable Long id){return service.detail(id);}
 @PostMapping(path="/images",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @PreAuthorize("hasRole('CUSTOMER')") public Map<String,String> uploadImage(Authentication a,@RequestPart("file") MultipartFile file){return Map.of("url",service.uploadImage(a.getName(),file));}
 @PostMapping("/listings/{id}/inquiries") @PreAuthorize("hasRole('CUSTOMER')") public ResponseEntity<Void> inquiry(Authentication a,@PathVariable Long id,@Valid @RequestBody MarketplaceInquiryRequest r){service.inquiry(a.getName(),id,r);return ResponseEntity.noContent().build();}
 @PostMapping("/listings/{id}/reports") @PreAuthorize("hasRole('CUSTOMER')") public ResponseEntity<Void> report(Authentication a,@PathVariable Long id,@Valid @RequestBody MarketplaceReportRequest r){service.report(a.getName(),id,r);return ResponseEntity.noContent().build();}
 @GetMapping("/my-listings") @PreAuthorize("hasRole('CUSTOMER')") public Page<MarketplaceListingResponse> mine(Authentication a,@RequestParam(defaultValue="0") int page){return service.mine(a.getName(),page);}
 @GetMapping("/my-inquiries") @PreAuthorize("hasRole('CUSTOMER')") public List<MarketplaceInquiry> mineInquiries(Authentication a){return service.ownerInquiries(a.getName());}
 @PostMapping("/listings") @PreAuthorize("hasRole('CUSTOMER')") public MarketplaceListingResponse create(Authentication a,@Valid @RequestBody MarketplaceListingRequest r){return service.create(a.getName(),r);}
 @PutMapping("/listings/{id}") @PreAuthorize("hasRole('CUSTOMER')") public MarketplaceListingResponse update(Authentication a,@PathVariable Long id,@Valid @RequestBody MarketplaceListingRequest r){return service.update(a.getName(),id,r);}
 @PostMapping("/listings/{id}/sold") @PreAuthorize("hasRole('CUSTOMER')") public MarketplaceListingResponse sold(Authentication a,@PathVariable Long id){return service.markSold(a.getName(),id);}
 @PostMapping("/listings/{id}/pause") @PreAuthorize("hasRole('CUSTOMER')") public MarketplaceListingResponse pause(Authentication a,@PathVariable Long id){return service.pause(a.getName(),id);}
 @DeleteMapping("/listings/{id}") @PreAuthorize("hasRole('CUSTOMER')") public ResponseEntity<Void> remove(Authentication a,@PathVariable Long id){service.remove(a.getName(),id);return ResponseEntity.noContent().build();}
 @GetMapping("/admin/listings") @PreAuthorize("hasRole('ADMIN')") public Page<MarketplaceListingResponse> admin(Authentication a,@RequestParam(required=false) MarketplaceListingStatus status,@RequestParam(defaultValue="0") int page){return service.admin(a.getName(),status,page);}
 @GetMapping("/admin/owners") @PreAuthorize("hasRole('ADMIN')") public Page<MarketplaceOwnerSummary> adminOwners(Authentication a,@RequestParam(defaultValue="0") int page){return service.adminOwners(a.getName(),page);}
 @GetMapping("/admin/inquiries") @PreAuthorize("hasRole('ADMIN')") public Page<MarketplaceAdminInquiryResponse> adminInquiries(Authentication a,@RequestParam(required=false) String status,@RequestParam(defaultValue="0") int page){return service.adminInquiries(a.getName(),status,page);}
 @PostMapping("/admin/listings/{id}/decision") @PreAuthorize("hasRole('ADMIN')") public MarketplaceListingResponse decide(Authentication a,@PathVariable Long id,@Valid @RequestBody MarketplaceDecisionRequest r){return service.decide(a.getName(),id,r);}
 @PostMapping("/admin/reports/{id}/resolve") @PreAuthorize("hasRole('ADMIN')") public ResponseEntity<Void> resolve(Authentication a,@PathVariable Long id,@RequestBody Map<String,Object> r){service.resolveReport(a.getName(),id,Boolean.TRUE.equals(r.get("resolved")),String.valueOf(r.getOrDefault("remarks", "")));return ResponseEntity.noContent().build();}
 @PostMapping("/admin/categories") @PreAuthorize("hasRole('ADMIN')") public MarketplaceCategory category(Authentication a,@RequestBody MarketplaceCategory r){return service.saveCategory(a.getName(),r);}
 @PostMapping("/admin/categories/{id}/subcategories") @PreAuthorize("hasRole('ADMIN')") public MarketplaceSubcategory subcategory(Authentication a,@PathVariable Long id,@RequestBody MarketplaceSubcategory r){return service.saveSubcategory(a.getName(),r,id);}
 @PostMapping("/admin/subcategories/{id}/fields") @PreAuthorize("hasRole('ADMIN')") public MarketplaceAttributeDefinition field(Authentication a,@PathVariable Long id,@RequestBody MarketplaceAttributeDefinition r){return service.saveField(a.getName(),r,id);}
}
