package com.shivhub.backend.service;

import java.math.BigDecimal; import java.time.*; import java.util.*;
import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.data.domain.*; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile;
import com.shivhub.backend.dto.*; import com.shivhub.backend.entity.*; import com.shivhub.backend.enums.*; import com.shivhub.backend.repository.*;

/** Separate customer-to-customer catalogue.  It never writes to the seller Product inventory. */
@Service
public class MarketplaceService {
 private final UserRepository users; private final MarketplaceCategoryRepository categories; private final MarketplaceSubcategoryRepository subcategories; private final MarketplaceAttributeDefinitionRepository definitions; private final MarketplaceListingRepository listings; private final MarketplaceListingImageRepository images; private final MarketplaceInquiryRepository inquiries; private final MarketplaceReportRepository reports; private final MarketplaceAuditLogRepository audit; private final ObjectMapper mapper; private final EmailService email; private final WhatsAppNotificationService whatsapp; private final FileStorageService storage;
 public MarketplaceService(UserRepository users,MarketplaceCategoryRepository categories,MarketplaceSubcategoryRepository subcategories,MarketplaceAttributeDefinitionRepository definitions,MarketplaceListingRepository listings,MarketplaceListingImageRepository images,MarketplaceInquiryRepository inquiries,MarketplaceReportRepository reports,MarketplaceAuditLogRepository audit,ObjectMapper mapper,EmailService email,WhatsAppNotificationService whatsapp,FileStorageService storage){this.users=users;this.categories=categories;this.subcategories=subcategories;this.definitions=definitions;this.listings=listings;this.images=images;this.inquiries=inquiries;this.reports=reports;this.audit=audit;this.mapper=mapper;this.email=email;this.whatsapp=whatsapp;this.storage=storage;}
 private User user(String emailAddress, Role role){User user=users.findByEmail(emailAddress).orElseThrow(()->new IllegalArgumentException("User not found"));if(user.getRole()!=role)throw new IllegalArgumentException("Access denied");return user;}
 public List<MarketplaceCategory> publicCategories(){return categories.findByActiveTrueOrderByNameAsc();}
 public List<MarketplaceSubcategory> subcategories(Long categoryId){return subcategories.findByCategoryIdAndActiveTrueOrderByNameAsc(categoryId);}
 public List<MarketplaceAttributeDefinition> fields(Long subcategoryId){return definitions.findBySubcategoryIdAndActiveTrueOrderByDisplayOrderAsc(subcategoryId);}
 @Transactional public String uploadImage(String emailAddress,MultipartFile file){return storage.storeMarketplaceImage(user(emailAddress,Role.CUSTOMER).getId(),file);}
 @Transactional public MarketplaceListingResponse create(String emailAddress,MarketplaceListingRequest request){User owner=user(emailAddress,Role.CUSTOMER); MarketplaceListing listing=new MarketplaceListing(); apply(listing,request,owner,true); listings.save(listing); syncImages(listing,request.getImageUrls()); log(listing,owner.getId(),"CREATED","Listing submitted by owner"); notify(owner,"Marketplace listing received","Your listing '"+listing.getTitle()+"' is pending admin approval."); notifyWhatsApp(owner,WhatsAppNotificationEvent.MARKETPLACE_LISTING_SUBMITTED,listing.getTitle(),List.of(owner.getName(),listing.getTitle()));return response(listing,true);}
 @Transactional public MarketplaceListingResponse update(String emailAddress,Long id,MarketplaceListingRequest request){User owner=user(emailAddress,Role.CUSTOMER);MarketplaceListing listing=owned(id,owner);if(!Set.of(MarketplaceListingStatus.DRAFT,MarketplaceListingStatus.PENDING_ADMIN_APPROVAL,MarketplaceListingStatus.REJECTED,MarketplaceListingStatus.ACTIVE).contains(listing.getStatus()))throw new IllegalArgumentException("This listing can no longer be edited");apply(listing,request,owner,false);if(listing.getStatus()==MarketplaceListingStatus.ACTIVE)listing.setStatus(MarketplaceListingStatus.PENDING_ADMIN_APPROVAL);listings.save(listing);syncImages(listing,request.getImageUrls());log(listing,owner.getId(),"UPDATED","Listing updated and queued for review");return response(listing,true);}
 @Transactional public MarketplaceListingResponse markSold(String emailAddress,Long id){User owner=user(emailAddress,Role.CUSTOMER);MarketplaceListing listing=owned(id,owner);if(listing.getStatus()!=MarketplaceListingStatus.ACTIVE)throw new IllegalArgumentException("Only active listings can be marked sold");listing.setStatus(MarketplaceListingStatus.SOLD);listing.setSoldAt(LocalDateTime.now());log(listing,owner.getId(),"SOLD","Marked sold by owner");notify(owner,"Marketplace listing marked sold","Your listing will be archived after 10 days.");notifyWhatsApp(owner,WhatsAppNotificationEvent.MARKETPLACE_ITEM_SOLD,listing.getTitle(),List.of(owner.getName(),listing.getTitle()));return response(listing,true);}
 @Transactional public MarketplaceListingResponse pause(String emailAddress,Long id){User owner=user(emailAddress,Role.CUSTOMER);MarketplaceListing listing=owned(id,owner);if(listing.getStatus()!=MarketplaceListingStatus.ACTIVE)throw new IllegalArgumentException("Only active listings can be paused");listing.setStatus(MarketplaceListingStatus.DRAFT);log(listing,owner.getId(),"PAUSED","Paused by owner");return response(listing,true);}
 @Transactional public void remove(String emailAddress,Long id){User owner=user(emailAddress,Role.CUSTOMER);MarketplaceListing listing=owned(id,owner);if(!Set.of(MarketplaceListingStatus.DRAFT,MarketplaceListingStatus.PENDING_ADMIN_APPROVAL,MarketplaceListingStatus.REJECTED).contains(listing.getStatus()))throw new IllegalArgumentException("Only pending or draft listings can be deleted");images.deleteByListingId(id);listings.delete(listing);}
 @Transactional(readOnly=true) public Page<MarketplaceListingResponse> mine(String emailAddress,int page){User owner=user(emailAddress,Role.CUSTOMER);return listings.findByOwnerIdOrderByCreatedAtDesc(owner.getId(),PageRequest.of(Math.max(0,page),20)).map(value->response(value,true));}
 @Transactional(readOnly=true) public Page<MarketplaceListingResponse> search(String q,Long categoryId,Long subcategoryId,String condition,String city,BigDecimal min,BigDecimal max,int page){return listings.publicSearch(MarketplaceListingStatus.ACTIVE,clean(q),categoryId,subcategoryId,blank(condition),blank(city),min,max,PageRequest.of(Math.max(0,page),20)).map(value->response(value,false));}
 @Transactional(readOnly=true) public MarketplaceListingResponse detail(Long id){MarketplaceListing listing=listings.findById(id).orElseThrow(()->new IllegalArgumentException("Listing not found"));if(listing.getStatus()!=MarketplaceListingStatus.ACTIVE)throw new IllegalArgumentException("Listing is not available");return response(listing,false);}
 @Transactional public void inquiry(String emailAddress,Long id,MarketplaceInquiryRequest request){User buyer=user(emailAddress,Role.CUSTOMER);MarketplaceListing listing=listings.findById(id).orElseThrow(()->new IllegalArgumentException("Listing not found"));if(listing.getStatus()!=MarketplaceListingStatus.ACTIVE)throw new IllegalArgumentException("Listing is not available");if(listing.getOwner().getId().equals(buyer.getId()))throw new IllegalArgumentException("You cannot contact yourself");MarketplaceInquiry row=new MarketplaceInquiry();row.setListing(listing);row.setBuyer(buyer);row.setMessage(request.getMessage().trim());inquiries.save(row);notify(listing.getOwner(),"New marketplace enquiry","A ShivHub customer sent an enquiry for '"+listing.getTitle()+"'. Open Second-hand Market to view it.");notifyWhatsApp(listing.getOwner(),WhatsAppNotificationEvent.MARKETPLACE_ENQUIRY,listing.getTitle(),List.of(listing.getOwner().getName(),listing.getTitle(),buyer.getName()));}
 @Transactional public void report(String emailAddress,Long id,MarketplaceReportRequest request){User reporter=user(emailAddress,Role.CUSTOMER);MarketplaceListing listing=listings.findById(id).orElseThrow(()->new IllegalArgumentException("Listing not found"));MarketplaceReport row=new MarketplaceReport();row.setListing(listing);row.setReporter(reporter);row.setReason(request.getReason().trim());row.setDetails(blank(request.getDetails()));reports.save(row);log(listing,reporter.getId(),"REPORTED",row.getReason());}
 @Transactional(readOnly=true) public List<MarketplaceInquiry> ownerInquiries(String emailAddress){return inquiries.findByListingOwnerIdOrderByCreatedAtDesc(user(emailAddress,Role.CUSTOMER).getId());}
 @Transactional(readOnly=true) public Page<MarketplaceListingResponse> admin(String emailAddress,MarketplaceListingStatus status,int page){user(emailAddress,Role.ADMIN);return listings.adminSearch(status,PageRequest.of(Math.max(0,page),25)).map(value->response(value,true));}
 @Transactional(readOnly=true) public Page<MarketplaceOwnerSummary> adminOwners(String emailAddress,int page){user(emailAddress,Role.ADMIN);return listings.adminOwnerIds(PageRequest.of(Math.max(0,page),25)).map(id->{User owner=users.findById(id).orElseThrow();return new MarketplaceOwnerSummary(owner.getId(),owner.getName(),owner.getEmail(),owner.getMobile(),owner.getCreatedAt(),listings.countByOwnerId(id),listings.countByOwnerIdAndStatus(id,MarketplaceListingStatus.ACTIVE),listings.countByOwnerIdAndStatus(id,MarketplaceListingStatus.SOLD),inquiries.countByListingOwnerId(id));});}
 @Transactional(readOnly=true) public Page<MarketplaceAdminInquiryResponse> adminInquiries(String emailAddress,String status,int page){user(emailAddress,Role.ADMIN);Page<MarketplaceInquiry> source=blank(status)==null?inquiries.findAllByOrderByCreatedAtDesc(PageRequest.of(Math.max(0,page),25)):inquiries.findByStatusOrderByCreatedAtDesc(status.trim().toUpperCase(),PageRequest.of(Math.max(0,page),25));return source.map(row->{MarketplaceListing listing=row.getListing();User owner=listing.getOwner(),buyer=row.getBuyer();return new MarketplaceAdminInquiryResponse(row.getId(),listing.getId(),listing.getTitle(),owner.getId(),owner.getName(),owner.getMobile(),buyer.getId(),buyer.getName(),buyer.getMobile(),buyer.getEmail(),row.getMessage(),row.getStatus(),row.getCreatedAt());});}
 @Transactional public MarketplaceListingResponse decide(String emailAddress,Long id,MarketplaceDecisionRequest request){User admin=user(emailAddress,Role.ADMIN);MarketplaceListing listing=listings.findById(id).orElseThrow(()->new IllegalArgumentException("Listing not found"));if(listing.getStatus()!=MarketplaceListingStatus.PENDING_ADMIN_APPROVAL)throw new IllegalArgumentException("Only pending listings can be reviewed");if(Boolean.TRUE.equals(request.getApproved())){listing.setStatus(MarketplaceListingStatus.ACTIVE);listing.setRejectionReason(null);listing.setExpiresAt(LocalDateTime.now().plusDays(listing.getListingDays()));log(listing,admin.getId(),"APPROVED",blank(request.getRemarks()));notify(listing.getOwner(),"Marketplace listing approved","Your listing '"+listing.getTitle()+"' is now live until "+listing.getExpiresAt().toLocalDate()+".");notifyWhatsApp(listing.getOwner(),WhatsAppNotificationEvent.MARKETPLACE_LISTING_APPROVED,listing.getTitle(),List.of(listing.getOwner().getName(),listing.getTitle(),listing.getExpiresAt().toLocalDate().toString()));}else{listing.setStatus(MarketplaceListingStatus.REJECTED);listing.setRejectionReason(blank(request.getRemarks()));log(listing,admin.getId(),"REJECTED",listing.getRejectionReason());notify(listing.getOwner(),"Marketplace listing needs changes",listing.getRejectionReason()==null?"Please edit and submit again.":listing.getRejectionReason());notifyWhatsApp(listing.getOwner(),WhatsAppNotificationEvent.MARKETPLACE_LISTING_REJECTED,listing.getTitle(),List.of(listing.getOwner().getName(),listing.getTitle(),listing.getRejectionReason()==null?"Please edit and submit again.":listing.getRejectionReason()));}return response(listing,true);}
 @Transactional public void resolveReport(String emailAddress,Long reportId,boolean resolved,String remarks){User admin=user(emailAddress,Role.ADMIN);MarketplaceReport report=reports.findById(reportId).orElseThrow(()->new IllegalArgumentException("Report not found"));report.setStatus(resolved?MarketplaceReportStatus.RESOLVED:MarketplaceReportStatus.REJECTED);report.setAdminRemarks(blank(remarks));log(report.getListing(),admin.getId(),"REPORT_"+report.getStatus(),blank(remarks));}
 @Transactional public MarketplaceCategory saveCategory(String emailAddress,MarketplaceCategory category){user(emailAddress,Role.ADMIN);if(category.getId()==null&&categories.existsByNameIgnoreCase(category.getName().trim()))throw new IllegalArgumentException("Marketplace category already exists");if(category.getMinListingDays()<1||category.getMaxListingDays()<category.getMinListingDays()||category.getMaxListingDays()>365)throw new IllegalArgumentException("Invalid listing duration range");category.setName(category.getName().trim());return categories.save(category);}
 @Transactional public MarketplaceSubcategory saveSubcategory(String emailAddress,MarketplaceSubcategory subcategory,Long categoryId){user(emailAddress,Role.ADMIN);subcategory.setCategory(categories.findById(categoryId).orElseThrow(()->new IllegalArgumentException("Category not found")));return subcategories.save(subcategory);}
 @Transactional public MarketplaceAttributeDefinition saveField(String emailAddress,MarketplaceAttributeDefinition field,Long subcategoryId){user(emailAddress,Role.ADMIN);field.setSubcategory(subcategories.findById(subcategoryId).orElseThrow(()->new IllegalArgumentException("Subcategory not found")));return definitions.save(field);}
 @Scheduled(cron="${shivhub.marketplace.lifecycle-cron:0 15 0 * * *}",zone="Asia/Kolkata") @Transactional public void lifecycle(){LocalDateTime now=LocalDateTime.now();for(MarketplaceListing listing:listings.findByStatusAndExpiresAtBefore(MarketplaceListingStatus.ACTIVE,now)){listing.setStatus(MarketplaceListingStatus.EXPIRED);log(listing,null,"EXPIRED","Listing duration ended");notify(listing.getOwner(),"Marketplace listing expired","Your listing '"+listing.getTitle()+"' has expired.");notifyWhatsApp(listing.getOwner(),WhatsAppNotificationEvent.MARKETPLACE_LISTING_EXPIRED,listing.getTitle(),List.of(listing.getOwner().getName(),listing.getTitle()));}for(MarketplaceListing listing:listings.findByStatusAndSoldAtBefore(MarketplaceListingStatus.SOLD,now.minusDays(10))){listing.setStatus(MarketplaceListingStatus.ARCHIVED);log(listing,null,"ARCHIVED","Sold listing archived after 10 days");notify(listing.getOwner(),"Marketplace listing archived","Your sold listing '"+listing.getTitle()+"' has been archived.");notifyWhatsApp(listing.getOwner(),WhatsAppNotificationEvent.MARKETPLACE_LISTING_ARCHIVED,listing.getTitle(),List.of(listing.getOwner().getName(),listing.getTitle()));}}
 private void apply(MarketplaceListing listing,MarketplaceListingRequest r,User owner,boolean create){MarketplaceCategory category=categories.findById(r.getCategoryId()).filter(MarketplaceCategory::isActive).orElseThrow(()->new IllegalArgumentException("Active marketplace category is required"));MarketplaceSubcategory sub=r.getSubcategoryId()==null?null:subcategories.findById(r.getSubcategoryId()).orElseThrow(()->new IllegalArgumentException("Subcategory not found"));if(sub!=null&&!sub.getCategory().getId().equals(category.getId()))throw new IllegalArgumentException("Subcategory does not belong to category");int days=r.getListingDays()==null?Math.min(10,category.getMaxListingDays()):r.getListingDays();if(days<category.getMinListingDays()||days>category.getMaxListingDays())throw new IllegalArgumentException("Listing duration must be between "+category.getMinListingDays()+" and "+category.getMaxListingDays()+" days");validateAttributes(sub,r.getAttributes());listing.setOwner(owner);listing.setCategory(category);listing.setSubcategory(sub);listing.setTitle(r.getTitle().trim());listing.setDescription(r.getDescription().trim());listing.setPrice(r.getPrice());listing.setNegotiable(r.isNegotiable());listing.setCondition(blank(r.getCondition()));listing.setBrand(blank(r.getBrand()));listing.setModel(blank(r.getModel()));listing.setYear(r.getYear());listing.setUsage(blank(r.getUsage()));listing.setLocation(blank(r.getLocation()));listing.setCity(blank(r.getCity()));listing.setDistrict(blank(r.getDistrict()));listing.setState(blank(r.getState()));listing.setContactPreference("INQUIRY");listing.setListingDays(days);listing.setAttributesJson(write(r.getAttributes()));if(create||r.isSubmitForApproval())listing.setStatus(r.isSubmitForApproval()?MarketplaceListingStatus.PENDING_ADMIN_APPROVAL:MarketplaceListingStatus.DRAFT);}
 private void syncImages(MarketplaceListing listing,List<String> urls){if(urls==null)return;if(urls.size()>8)throw new IllegalArgumentException("Maximum 8 listing images");images.deleteByListingId(listing.getId());for(int i=0;i<urls.size();i++)saveImage(listing,urls.get(i),i);}
 private void saveImage(MarketplaceListing listing,String url,int order){String safe=blank(url);if(safe==null||!(safe.startsWith("/")||safe.matches("https?://.*")))throw new IllegalArgumentException("Listing image must be an upload path or HTTP URL");MarketplaceListingImage image=new MarketplaceListingImage();image.setListing(listing);image.setImageUrl(safe);image.setDisplayOrder(order);images.save(image);}
 private void validateAttributes(MarketplaceSubcategory sub,Map<String,String> values){if(sub==null)return;Map<String,String> safe=values==null?Map.of():values;List<MarketplaceAttributeDefinition> fields=definitions.findBySubcategoryIdAndActiveTrueOrderByDisplayOrderAsc(sub.getId());Set<String> keys=new HashSet<>();for(MarketplaceAttributeDefinition f:fields){keys.add(f.getAttributeKey());String value=blank(safe.get(f.getAttributeKey()));if(f.isRequiredField()&&value==null)throw new IllegalArgumentException(f.getDisplayName()+" is required");if(value!=null&&value.length()>4000)throw new IllegalArgumentException(f.getDisplayName()+" is too long");}if(!keys.containsAll(safe.keySet()))throw new IllegalArgumentException("Listing contains an unconfigured field");}
 private MarketplaceListing owned(Long id,User owner){MarketplaceListing listing=listings.findById(id).orElseThrow(()->new IllegalArgumentException("Listing not found"));if(!listing.getOwner().getId().equals(owner.getId()))throw new IllegalArgumentException("Listing does not belong to you");return listing;} private void log(MarketplaceListing l,Long actor,String action,String remarks){MarketplaceAuditLog row=new MarketplaceAuditLog();row.setListing(l);row.setActorId(actor);row.setAction(action);row.setRemarks(remarks);audit.save(row);} private void notify(User user,String subject,String body){try{if(user.getEmail()!=null&&!user.getEmail().isBlank())email.sendFinanceNotification(user.getEmail(),subject,body);}catch(Exception ignored){}} private void notifyWhatsApp(User user,WhatsAppNotificationEvent event,String reference,List<String> parameters){try{if(user.getEmail()!=null&&!user.getEmail().isBlank())whatsapp.sendCustomerEvent(user.getEmail(),event,user.getName(),reference,parameters);}catch(Exception ignored){}} private String clean(String s){return s==null?"":s.trim();} private String blank(String s){return s==null||s.isBlank()?null:s.trim();} private String write(Map<String,String> v){try{return mapper.writeValueAsString(v==null?Map.of():v);}catch(Exception e){throw new IllegalArgumentException("Invalid listing fields");}} private Map<String,String> read(String raw){try{return raw==null?Map.of():mapper.readValue(raw,new TypeReference<Map<String,String>>(){});}catch(Exception e){return Map.of();}} private MarketplaceListingResponse response(MarketplaceListing l,boolean owner){List<String> urls=images.findByListingIdOrderByDisplayOrderAsc(l.getId()).stream().map(MarketplaceListingImage::getImageUrl).toList();return new MarketplaceListingResponse(l.getId(),l.getTitle(),l.getDescription(),l.getPrice(),l.isNegotiable(),l.getCondition(),l.getBrand(),l.getModel(),l.getYear(),l.getUsage(),l.getLocation(),l.getCity(),l.getDistrict(),l.getState(),l.getContactPreference(),l.getCategory().getId(),l.getCategory().getName(),l.getSubcategory()==null?null:l.getSubcategory().getId(),l.getSubcategory()==null?null:l.getSubcategory().getName(),l.getStatus(),l.getRejectionReason(),l.getListingDays(),l.getExpiresAt(),l.getSoldAt(),l.getCreatedAt(),read(l.getAttributesJson()),urls,owner?l.getOwner().getName():null,owner);}
}
