package com.shivhub.backend.enums;

public enum AfterSalesInspectionFinding {
    MANUFACTURING_DEFECT, PHYSICAL_DAMAGE, LIQUID_DAMAGE, SOFTWARE_ISSUE,
    ACCESSORY_DAMAGE, CUSTOMER_MISUSE, TAMPERED, UNAUTHORIZED_REPAIR, NO_FAULT_FOUND
}
