package com.shivhub.backend.enums;

public enum AfterSalesNotificationType {
    REQUEST_CREATED, REQUEST_APPROVED, REQUEST_REJECTED, PRODUCT_RECEIVED, ESTIMATE_READY,
    ESTIMATE_APPROVED, ESTIMATE_REJECTED, SENT_TO_SERVICE_CENTER, REPAIR_COMPLETED,
    REPLACEMENT_READY, REPLACEMENT_COMPLETED, REFUND_INITIATED, REFUND_COMPLETED,
    READY_FOR_PICKUP, REQUEST_CLOSED, STATUS_UPDATED
}
