package com.shivhub.backend.enums;

public enum ServiceRequestStatus {
    REQUESTED, UNDER_REVIEW, ELIGIBILITY_CHECK, APPROVED, REJECTED, PRODUCT_RECEIVED,
    INSPECTION_IN_PROGRESS, WARRANTY_CONFIRMED, PAID_REPAIR_APPROVAL_REQUIRED,
    ESTIMATE_APPROVED, ESTIMATE_REJECTED, SENT_TO_SERVICE_CENTER, REPAIR_IN_PROGRESS,
    READY_FOR_DELIVERY, DELIVERED, CLOSED, CANCELLED, INSPECTION_PASSED,
    INSPECTION_FAILED, RETURN_APPROVED, REPLACEMENT_APPROVED, REFUND_INITIATED,
    REFUNDED, REPLACED, COMPLETED
}
