import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import api, { API_BASE_URL } from "../../services/api";
import { getPendingSellers, approveProduct, rejectProduct } from "../../services/adminService";
import "./AdminManagement.css";

const TABS = [
  ["SELLERS", "Seller approvals", "New shop/seller applications"],
  ["PRODUCTS", "Product approvals", "Direct seller product submissions"],
  ["PURCHASES", "Purchase-source approvals", "Supplier invoices with products waiting for review"],
  ["MARKETPLACE", "Second-hand listings", "Customer listings waiting for moderation"],
];

const money = value => Number(value || 0).toLocaleString("en-IN", {
  style: "currency", currency: "INR", maximumFractionDigits: 2
});
const date = value => value ? new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "—";
const fileUrl = value => !value || /^https?:\/\//i.test(value) ? value : `${API_BASE_URL}/${String(value).replace(/^\/+/, "")}`;

export default function AdminApprovals() {
  const [tab, setTab] = useState("SELLERS"); const [rows, setRows] = useState([]); const [sourceRows, setSourceRows] = useState([]); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setError(""); try { if (tab === "SELLERS") { setRows(await getPendingSellers()); setSourceRows([]); } else if (tab === "PRODUCTS") { setRows((await api.get("/api/admin/products/pending")).data); setSourceRows([]); } else if (tab === "PURCHASES") { const [purchases, sources] = await Promise.all([api.get("/api/admin/purchase-approvals"), api.get("/api/admin/distributors/pending")]); setRows(purchases.data || []); setSourceRows(sources.data || []); } else { setRows((await api.get("/api/marketplace/admin/listings", { params: { status: "PENDING_ADMIN_APPROVAL" } })).data.content || []); setSourceRows([]); } } catch (e) { setError(e.response?.data?.message || "Approval queue could not be loaded."); } }, [tab]);
  useEffect(() => { void load(); }, [load]);
  const productDecision = async (id, approved) => { const reason = approved ? "Approved by admin" : window.prompt("Rejection reason"); if (!approved && !reason?.trim()) return; setBusy(`product-${id}`); try { approved ? await approveProduct(id, reason) : await rejectProduct(id, reason); await load(); } catch (e) { setError(e.response?.data?.message || "Product decision could not be saved."); } finally { setBusy(""); } };
  const purchaseDecision = async purchase => { setBusy(`purchase-${purchase.purchaseId}`); setError(""); try { await api.post(`/api/admin/purchase-approvals/${purchase.purchaseId}/approve`, { review: `Purchase invoice ${purchase.invoiceNumber} approved by admin.` }); setNotice(`Invoice ${purchase.invoiceNumber} and its ${purchase.pendingProductCount} pending product(s) were approved.`); await load(); } catch (e) { setError(e.response?.data?.message || "Purchase approval could not be saved."); } finally { setBusy(""); } };
  const distributorDecision = async (id, approved) => { const review = approved ? "Approved by admin" : window.prompt("Rejection reason"); if (!approved && !review?.trim()) return; setBusy(`source-${id}`); try { await api.patch(`/api/admin/distributors/${id}/${approved ? "approve" : "reject"}`, { review }); await load(); } catch (e) { setError(e.response?.data?.message || "Purchase-source decision could not be saved."); } finally { setBusy(""); } };
  const marketDecision = async (id, approved) => { const remarks = approved ? "Approved by admin" : window.prompt("Rejection reason"); if (!approved && !remarks?.trim()) return; setBusy(`market-${id}`); try { await api.post(`/api/marketplace/admin/listings/${id}/decision`, { approved, remarks }); await load(); } catch (e) { setError(e.response?.data?.message || "Listing decision could not be saved."); } finally { setBusy(""); } };
  const active = TABS.find(item => item[0] === tab);
  return <main className="admin-management"><header><div><p className="eyebrow">ADMIN CONTROL</p><h1>Approvals centre</h1><p>Separate queues for sellers, direct product submissions, supplier invoices and customer listings.</p></div><Link className="back-link" to="/admin/dashboard">Dashboard</Link></header><div className="website-tabs" role="tablist">{TABS.map(([value, label, help]) => <button key={value} className={tab === value ? "active" : ""} onClick={() => setTab(value)} title={help}>{label}</button>)}</div><section className="management-card"><h2>{active?.[1]}</h2><p>{active?.[2]}</p>{error && <p className="admin-error">{error}</p>}{notice && <p className="admin-success">{notice}</p>}
    {tab === "SELLERS" && <table><thead><tr><th>Applicant</th><th>Email</th><th>Mobile</th><th /></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><strong>{row.name}</strong></td><td>{row.email}</td><td>{row.mobile || "—"}</td><td><Link className="primary-link" to={`/admin/seller-requests/${row.id}`}>Review</Link></td></tr>)}</tbody></table>}
    {tab === "PRODUCTS" && <table><thead><tr><th>Product</th><th>Category</th><th>Seller</th><th>Price</th><th /></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><strong>{row.name}</strong></td><td>{row.category || "Uncategorised"}</td><td>{row.seller?.name || "ShivHub"}</td><td>₹{Number(row.price || 0).toLocaleString("en-IN")}</td><td className="decision-actions"><button disabled={!!busy} className="approve" onClick={() => void productDecision(row.id, true)}>Approve</button><button disabled={!!busy} className="reject" onClick={() => void productDecision(row.id, false)}>Reject</button></td></tr>)}</tbody></table>}
    {tab === "PURCHASES" && <>
      <h3>Purchase invoices waiting for approval</h3>
      <p>Review who supplied whom, the bill value and every received product. Approving an invoice approves only the pending products on that invoice.</p>
      <table><thead><tr><th>Invoice & submitted</th><th>Supplier → seller</th><th>Bill amount</th><th>Pending products</th><th>Invoice details</th><th /></tr></thead><tbody>{rows.map(purchase => <tr key={purchase.purchaseId}><td><strong>{purchase.invoiceNumber}</strong><small>Purchase: {date(purchase.purchaseDate)}<br />Submitted: {date(purchase.submittedAt)}</small></td><td><strong>{purchase.supplierName || "Supplier"}</strong><small>{purchase.supplierGstin || "No GSTIN"} · {purchase.supplierContact || "No contact"}<br />To: {purchase.sellerName || "Seller"}<br />{purchase.sellerEmail || purchase.sellerMobile || "—"}</small></td><td><strong>{money(purchase.grandTotal)}</strong><small>Taxable: {money(purchase.subtotal)}<br />GST: {money(purchase.gstTotal)}<br />Discount: {money(purchase.discount)}</small></td><td><strong>{purchase.pendingProductCount} awaiting</strong><small>{purchase.items?.filter(item => item.pendingProductApproval).map(item => `${item.productName} × ${item.quantity}`).join(", ") || "—"}</small></td><td><details><summary>View {purchase.items?.length || 0} bill item(s)</summary><table><thead><tr><th>Product</th><th>Configuration</th><th>Qty</th><th>Rate</th><th>Total</th></tr></thead><tbody>{purchase.items?.map((item, index) => <tr key={`${purchase.purchaseId}-${item.productId || index}`}><td><strong>{item.productName}</strong><small>{item.sku || "No SKU"}{item.pendingProductApproval ? " · Pending approval" : ""}</small></td><td>{[item.brand, item.model, item.color, item.ram, item.storage].filter(Boolean).join(" · ") || "—"}</td><td>{item.quantity} {item.unit || "NOS"}</td><td>{money(item.unitPrice)}</td><td>{money(item.totalPrice)}</td></tr>)}</tbody></table>{purchase.invoiceFileUrl && <a className="primary-link" href={fileUrl(purchase.invoiceFileUrl)} target="_blank" rel="noreferrer">Open uploaded invoice</a>}{purchase.notes && <p><strong>Seller note:</strong> {purchase.notes}</p>}</details></td><td className="decision-actions"><button disabled={!!busy} className="approve" onClick={() => void purchaseDecision(purchase)}>{busy === `purchase-${purchase.purchaseId}` ? "Approving…" : "Approve invoice & products"}</button></td></tr>)}</tbody></table>
      {sourceRows.length > 0 && <><h3>Supplier/distributor access requests</h3><p>These are supplier requests submitted before purchase use.</p><table><thead><tr><th>Supplier / distributor</th><th>GSTIN</th><th>Contact</th><th>Requested by</th><th /></tr></thead><tbody>{sourceRows.map(row => <tr key={row.id}><td><strong>{row.businessName || row.name}</strong></td><td>{row.gstin || "—"}</td><td>{row.mobile || row.email || "—"}</td><td>{row.requestedByName || "Seller"}</td><td className="decision-actions"><button disabled={!!busy} className="approve" onClick={() => void distributorDecision(row.id, true)}>{busy === `source-${row.id}` ? "Approving…" : "Approve"}</button><button disabled={!!busy} className="reject" onClick={() => void distributorDecision(row.id, false)}>Reject</button></td></tr>)}</tbody></table></>}
    </>}
    {tab === "MARKETPLACE" && <table><thead><tr><th>Listing</th><th>Category</th><th>Owner</th><th>Price</th><th /></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><strong>{row.title}</strong></td><td>{row.categoryName || "—"}</td><td>{row.ownerName || "Customer"}</td><td>₹{Number(row.price || 0).toLocaleString("en-IN")}</td><td className="decision-actions"><button disabled={!!busy} className="approve" onClick={() => void marketDecision(row.id, true)}>Approve</button><button disabled={!!busy} className="reject" onClick={() => void marketDecision(row.id, false)}>Reject</button></td></tr>)}</tbody></table>}
    {tab === "PURCHASES" ? !rows.length && !sourceRows.length && !error && <p className="empty">No purchase invoice or supplier request is waiting for approval.</p> : !rows.length && !error && <p className="empty">No requests are waiting in this queue.</p>}</section></main>;
}
