import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getAdminCustomer } from "../../services/adminManagementService";
import "./AdminGrowth.css";

const money = value => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value || 0));
const date = value => value ? new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "—";

export default function AdminCustomerDetails() {
  const { id } = useParams(); const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { getAdminCustomer(id).then(setData).catch(() => setError("Customer profile could not be loaded.")); }, [id]);
  if (!data && !error) return <main className="growth-page"><p>Loading customer profile…</p></main>;
  const customer = data?.customer; return <main className="growth-page"><Link className="back-link" to="/admin/customers">← All Customers</Link>{error && <p className="growth-error">{error}</p>}{customer && <><header className="profile-hero"><div className="avatar-large">{customer.name?.slice(0, 1)}</div><div><p className="eyebrow">Unified customer profile · #{customer.id}</p><h1>{customer.name}</h1><p>{customer.mobile || "No mobile"} · {customer.email || "No email"}</p><span className="pill neutral">{customer.customerType}</span></div></header><section className="metric-grid compact"><article><span>Orders & bills</span><strong>{customer.totalOrdersAndBills}</strong></article><article><span>Total purchased</span><strong>{money(customer.totalPurchaseAmount)}</strong></article><article><span>Pending receivable</span><strong>{money(customer.pendingReceivable)}</strong></article><article><span>Last purchase</span><strong>{date(customer.lastPurchaseDate)}</strong></article></section><section className="detail-columns"><article className="growth-card"><h2>Contact & consent</h2><dl className="detail-list"><dt>Address</dt><dd>{customer.address || "Not provided"}</dd><dt>Account</dt><dd>{customer.onlineUserId ? customer.accountEnabled ? "Online account active" : "Online account blocked" : "Walk-in / seller customer"}</dd><dt>Marketing consent</dt><dd>{data.communication.consent ? "Granted" : "Opted out"}</dd><dt>Online marketing</dt><dd>{data.communication.onlineMarketingOptOut ? "Opted out" : "Allowed"}</dd></dl></article><article className="growth-card"><h2>Associated sellers</h2><div className="mini-list">{data.associatedSellers.map(seller => <Link key={seller.sellerId} to={`/admin/sellers/${seller.sellerId}`}><strong>{seller.businessName || seller.sellerName}</strong><span>First purchase {date(seller.firstPurchaseAt)} · Last {date(seller.lastPurchaseAt)}</span></Link>)}{!data.associatedSellers.length && <p className="empty-state">No seller relationships yet.</p>}</div></article></section><section className="growth-card"><h2>Purchase timeline</h2><div className="timeline">{data.purchaseHistory.map(purchase => <article key={`${purchase.type}-${purchase.id}`}><div><span className="pill neutral">{purchase.type}</span><strong>{purchase.reference}</strong><small>{date(purchase.date)} · {purchase.paymentStatus}</small></div><div className="timeline-products">{purchase.products?.map((product, index) => <span key={`${product.name}-${index}`}>{product.name} × {product.quantity}</span>)}</div><b>{money(purchase.amount)}</b></article>)}{!data.purchaseHistory.length && <p className="empty-state">No linked purchase history yet.</p>}</div></section></>}</main>;
}
