import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { extendSellerSubscription, getAdminSellerSubscriptions, getAdminSubscriptionFeatures, getAdminSubscriptionOverview, getAdminSubscriptionPayments, getAdminSubscriptionPlans, saveAdminSubscriptionPlan, setSellerSubscriptionSuspended } from "../../services/subscriptionService";
import "./AdminSubscriptions.css";

const blankPlan = { name: "", code: "", description: "", price: "", currency: "INR", billingInterval: "MONTH", billingIntervalCount: 1, trialMonths: 0, active: true, recommended: false, displayOrder: 0, featureCodes: [] };
const money = value => `₹${Number(value || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const date = value => value ? new Date(`${value}T00:00:00`).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "—";

export default function AdminSubscriptions() {
    const [overview, setOverview] = useState(null); const [plans, setPlans] = useState([]); const [features, setFeatures] = useState([]); const [sellers, setSellers] = useState([]); const [payments, setPayments] = useState([]);
    const [plan, setPlan] = useState(blankPlan); const [editingId, setEditingId] = useState(null); const [selectedSeller, setSelectedSeller] = useState(null); const [action, setAction] = useState({ extensionDays: 30, reason: "" });
    const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
    const load = useCallback(async () => { setLoading(true); setError(""); try { const [a, b, c, d, e] = await Promise.all([getAdminSubscriptionOverview(), getAdminSubscriptionPlans(), getAdminSubscriptionFeatures(), getAdminSellerSubscriptions(), getAdminSubscriptionPayments()]); setOverview(a || {}); setPlans(Array.isArray(b) ? b : []); setFeatures(Array.isArray(c) ? c : []); setSellers(Array.isArray(d) ? d : []); setPayments(Array.isArray(e) ? e : []); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to load subscription administration."); } finally { setLoading(false); } }, []);
    useEffect(() => { void load(); }, [load]);
    const groups = useMemo(() => features.reduce((result, feature) => { const key = feature.category || "OTHER"; (result[key] ||= []).push(feature); return result; }, {}), [features]);
    const change = event => { const { name, value, checked, type } = event.target; setPlan(current => ({ ...current, [name]: type === "checkbox" ? checked : value })); };
    const toggleFeature = featureCode => setPlan(current => ({ ...current, featureCodes: current.featureCodes.includes(featureCode) ? current.featureCodes.filter(value => value !== featureCode) : [...current.featureCodes, featureCode] }));
    const editPlan = item => { setEditingId(item.id); setPlan({ ...blankPlan, ...item, price: item.price ?? "", featureCodes: Array.isArray(item.featureCodes) ? item.featureCodes : [] }); window.scrollTo({ top: 0, behavior: "smooth" }); };
    const save = async event => { event.preventDefault(); setSaving(true); setError(""); setNotice(""); try { await saveAdminSubscriptionPlan(editingId, { ...plan, price: Number(plan.price), billingIntervalCount: Number(plan.billingIntervalCount), trialMonths: Number(plan.trialMonths), displayOrder: Number(plan.displayOrder) }); setPlan(blankPlan); setEditingId(null); setNotice("Plan saved. Existing paid sellers keep their current entitlement snapshot until renewal."); await load(); } catch (requestError) { setError(requestError.response?.data?.message || "Plan could not be saved."); } finally { setSaving(false); } };
    const runSellerAction = async (suspended = false) => { if (!selectedSeller) return; setSaving(true); setError(""); try { const payload = { extensionDays: Number(action.extensionDays), reason: action.reason || "Admin subscription action" }; if (suspended) await setSellerSubscriptionSuspended(selectedSeller.sellerId, true, payload); else if (selectedSeller.status === "SUSPENDED") await setSellerSubscriptionSuspended(selectedSeller.sellerId, false, payload); else await extendSellerSubscription(selectedSeller.sellerId, payload); setNotice("Seller subscription updated."); setSelectedSeller(null); await load(); } catch (requestError) { setError(requestError.response?.data?.message || "Seller subscription could not be updated."); } finally { setSaving(false); } };
    const metrics = [["Total sellers", overview?.totalSellers], ["Free trial", overview?.trial], ["Active paid", overview?.active], ["Payment due", overview?.payment_pending], ["Expired", overview?.expired], ["Trials ending soon", overview?.trialsEndingSoon], ["Renewals due", overview?.renewalsDue], ["Today revenue", money(overview?.todayRevenue)], ["This month", money(overview?.monthlyRevenue)], ["Total revenue", money(overview?.totalRevenue)]];
    return <main className="admin-subscriptions">
        <header><div><p className="admin-subscription-eyebrow">SHIVHUB ADMIN</p><h1>Subscriptions</h1><p>Control seller plans, modules and commercial access without affecting seller business data.</p></div><Link to="/admin/settings">Admin settings</Link></header>
        {error && <p className="admin-subscription-message error">{error}</p>}{notice && <p className="admin-subscription-message success">{notice}</p>}
        {loading ? <section className="admin-subscription-loading">Loading subscription controls…</section> : <>
            <section className="admin-subscription-kpis">{metrics.map(([label, value]) => <article key={label}><small>{label}</small><strong>{value ?? 0}</strong></article>)}</section>
            <section className="admin-subscription-layout"><form className="admin-plan-builder" onSubmit={save}><div className="admin-section-heading"><div><p className="admin-subscription-eyebrow">PLANS & MODULES</p><h2>{editingId ? "Edit plan" : "Create plan"}</h2></div>{editingId && <button type="button" className="plain" onClick={() => { setPlan(blankPlan); setEditingId(null); }}>Cancel edit</button>}</div><div className="admin-plan-fields"><label>Plan name<input name="name" required value={plan.name} onChange={change} /></label><label>Plan code<input name="code" required value={plan.code} onChange={change} /></label><label>Price<input name="price" required min="0" step="0.01" type="number" value={plan.price} onChange={change} /></label><label>Currency<input name="currency" required maxLength="3" value={plan.currency} onChange={change} /></label><label>Billing interval<select name="billingInterval" value={plan.billingInterval} onChange={change}>{["MONTH", "QUARTER", "HALF_YEAR", "YEAR"].map(value => <option key={value} value={value}>{value.replace("_", " ")}</option>)}</select></label><label>Interval count<input name="billingIntervalCount" min="1" type="number" value={plan.billingIntervalCount} onChange={change} /></label><label>Display order<input name="displayOrder" min="0" type="number" value={plan.displayOrder} onChange={change} /></label><label className="wide">Description<textarea name="description" value={plan.description || ""} onChange={change} /></label></div><div className="admin-plan-checks"><label><input type="checkbox" name="active" checked={plan.active} onChange={change} /> Available to sellers</label><label><input type="checkbox" name="recommended" checked={plan.recommended} onChange={change} /> Recommended plan</label></div><h3>Module access</h3><p className="module-helper">A paid seller receives a snapshot of these selected modules. System-required access cannot be removed here.</p><div className="admin-feature-groups">{Object.entries(groups).map(([group, list]) => <fieldset key={group}><legend>{group}</legend>{list.map(feature => <label key={feature.featureCode}><input type="checkbox" checked={plan.featureCodes.includes(feature.featureCode)} onChange={() => toggleFeature(feature.featureCode)} /> {feature.featureName}</label>)}</fieldset>)}</div><button className="admin-primary" disabled={saving}>{saving ? "Saving…" : editingId ? "Save plan changes" : "Create plan"}</button></form>
                <section className="admin-plan-list"><div className="admin-section-heading"><div><p className="admin-subscription-eyebrow">CONFIGURED PLANS</p><h2>Plan catalogue</h2></div></div>{plans.length ? plans.map(item => <article key={item.id}><div><strong>{item.name}</strong>{item.recommended && <span>Recommended</span>}<p>{money(item.price)} / {String(item.billingInterval).toLowerCase()}</p><small>{(item.featureCodes || []).length} modules · {item.active ? "Active" : "Inactive"}</small></div><button onClick={() => editPlan(item)}>Edit</button></article>) : <p>No plans configured.</p>}</section></section>
            <section className="admin-seller-subscriptions"><div className="admin-section-heading"><div><p className="admin-subscription-eyebrow">SELLER SUBSCRIPTIONS</p><h2>Access & renewal status</h2></div></div><div className="admin-subscription-table"><table><thead><tr><th>Shop / owner</th><th>Plan</th><th>Status</th><th>Trial / expiry</th><th>Next payment</th><th>Actions</th></tr></thead><tbody>{sellers.map(seller => <tr key={seller.sellerId}><td><strong>{seller.shopName || "—"}</strong><small>{seller.sellerName}</small></td><td>{seller.currentPlan?.name || "Free trial / legacy"}</td><td><span className={`admin-sub-status ${String(seller.status).toLowerCase()}`}>{seller.status.replace("_", " ")}</span></td><td>{seller.status === "TRIAL" ? date(seller.trialEndDate) : date(seller.subscriptionEndDate)}</td><td>{date(seller.nextBillingDate)}</td><td><button onClick={() => { setSelectedSeller(seller); setAction({ extensionDays: 30, reason: "" }); }}>Manage</button></td></tr>)}</tbody></table></div></section>
            {selectedSeller && <section className="admin-seller-action"><div><p className="admin-subscription-eyebrow">SELLER CONTROL</p><h2>{selectedSeller.shopName || selectedSeller.sellerName}</h2><p>Actions are recorded as an audit event; payment history is never altered.</p></div><label>Complimentary extension (days)<input type="number" min="1" max="3650" value={action.extensionDays} onChange={event => setAction(current => ({ ...current, extensionDays: event.target.value }))} /></label><label>Reason<textarea required value={action.reason} onChange={event => setAction(current => ({ ...current, reason: event.target.value }))} /></label><div><button className="admin-primary" disabled={saving} onClick={() => runSellerAction(false)}>{selectedSeller.status === "SUSPENDED" ? "Reactivate" : "Grant extension"}</button>{selectedSeller.status !== "SUSPENDED" && <button className="admin-danger" disabled={saving} onClick={() => runSellerAction(true)}>Suspend seller access</button>}<button className="plain" onClick={() => setSelectedSeller(null)}>Cancel</button></div></section>}
            <section className="admin-subscription-payments"><div className="admin-section-heading"><div><p className="admin-subscription-eyebrow">PAYMENTS</p><h2>Verified subscription collections</h2></div></div><div className="admin-subscription-table"><table><thead><tr><th>Date</th><th>Seller plan</th><th>Amount</th><th>Gateway payment</th><th>Status</th><th>Period</th></tr></thead><tbody>{payments.length ? payments.map(payment => <tr key={payment.id}><td>{payment.paidAt ? new Date(payment.paidAt).toLocaleDateString("en-IN") : "—"}</td><td>{payment.planName}</td><td>{money(payment.amount)}</td><td>{payment.gatewayPaymentId || "—"}</td><td>{payment.paymentStatus}</td><td>{date(payment.billingPeriodStart)} – {date(payment.billingPeriodEnd)}</td></tr>) : <tr><td colSpan="6">No subscription payments have been received.</td></tr>}</tbody></table></div></section>
        </>}
    </main>;
}
