import { useCallback, useEffect, useMemo, useState } from "react";
import { afterSalesService } from "../../services/afterSalesService";
import "./AfterSalesManagement.css";

const EMPTY_POLICY = { warrantyType: "MANUFACTURER", warrantyMonths: 12, returnable: true, returnWindowDays: 7, replacementWindowDays: 7, doaWindowDays: 2, physicalDamageAllowed: false, liquidDamageAllowed: false, openedBoxReturnAllowed: false, changeOfMindAllowed: false, requiredEvidence: "", policyTerms: "", active: true };
const REQUEST_VIEWS = [["ALL", "All requests"], ["WARRANTY_CLAIM", "Warranty"], ["PAID_REPAIR", "Paid repairs"], ["RETURN", "Returns"], ["REPLACEMENT", "Replacements"], ["REFUND", "Refunds"], ["DOA_MANUFACTURING_DEFECT", "DOA"]];
const STATUSES = ["REQUESTED", "UNDER_REVIEW", "ELIGIBILITY_CHECK", "APPROVED", "REJECTED", "PRODUCT_RECEIVED", "INSPECTION_IN_PROGRESS", "WARRANTY_CONFIRMED", "PAID_REPAIR_APPROVAL_REQUIRED", "ESTIMATE_APPROVED", "ESTIMATE_REJECTED", "SENT_TO_SERVICE_CENTER", "REPAIR_IN_PROGRESS", "READY_FOR_DELIVERY", "INSPECTION_PASSED", "INSPECTION_FAILED", "RETURN_APPROVED", "REPLACEMENT_APPROVED", "REFUND_INITIATED", "REFUNDED", "REPLACED", "DELIVERED", "COMPLETED", "CLOSED", "CANCELLED"];
const label = value => String(value || "-").replaceAll("_", " ");
const date = value => value ? new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "-";
const number = value => new Intl.NumberFormat("en-IN").format(Number(value || 0));

export default function AfterSalesManagement() {
    const [policies, setPolicies] = useState([]); const [requests, setRequests] = useState([]); const [report, setReport] = useState({});
    const [policy, setPolicy] = useState(EMPTY_POLICY); const [editingPolicy, setEditingPolicy] = useState(null);
    const [activeView, setActiveView] = useState("ALL"); const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
    const [selected, setSelected] = useState(null); const [overrideStatus, setOverrideStatus] = useState(""); const [overrideReason, setOverrideReason] = useState(""); const [customerVisible, setCustomerVisible] = useState(true);
    const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");

    const load = useCallback(async (filters = { status, from, to }) => {
        setLoading(true); setError(""); const params = Object.fromEntries(Object.entries(filters).filter(([, value]) => value));
        try { const [policyResponse, requestResponse, reportResponse] = await Promise.all([afterSalesService.adminPolicies(), afterSalesService.adminRequests(params), afterSalesService.adminReport(params)]); setPolicies(Array.isArray(policyResponse.data) ? policyResponse.data : []); setRequests(Array.isArray(requestResponse.data) ? requestResponse.data : []); setReport(reportResponse.data || {}); }
        catch (requestError) { setError(requestError.response?.data?.message || "Could not load after-sales administration."); }
        finally { setLoading(false); }
    }, [status, from, to]);
    useEffect(() => { void load({}); }, [load]);

    const visibleRequests = useMemo(() => { const text = query.trim().toLowerCase(); return requests.filter(item => { const matchesView = activeView === "ALL" || item.requestType === activeView; const searchable = `${item.requestNumber} ${item.productName} ${item.sellerId || ""} ${item.orderId || ""} ${item.offlineBillId || ""} ${item.maskedSerial || ""}`.toLowerCase(); return matchesView && (!text || searchable.includes(text)); }); }, [activeView, query, requests]);
    const applyFilters = event => { event.preventDefault(); void load(); };
    const policyField = (key, title, type = "number") => <label>{title}<input type={type} min={type === "number" ? 0 : undefined} value={policy[key] ?? ""} onChange={event => setPolicy(current => ({ ...current, [key]: event.target.value }))} /></label>;

    const savePolicy = async event => { event.preventDefault(); setSaving(true); setError(""); try { await afterSalesService.saveAdminPolicy(editingPolicy?.id, { ...policy, categoryId: policy.categoryId ? Number(policy.categoryId) : null, productId: policy.productId ? Number(policy.productId) : null, warrantyMonths: Number(policy.warrantyMonths), returnWindowDays: Number(policy.returnWindowDays), replacementWindowDays: Number(policy.replacementWindowDays), doaWindowDays: Number(policy.doaWindowDays) }); setNotice("After-sales policy saved."); setPolicy(EMPTY_POLICY); setEditingPolicy(null); await load(); } catch (requestError) { setError(requestError.response?.data?.message || "Policy could not be saved."); } finally { setSaving(false); } };
    const deactivatePolicy = async id => { if (!window.confirm("Deactivate this policy? Existing completed sales are not changed.")) return; try { await afterSalesService.deactivateAdminPolicy(id); setNotice("Policy deactivated."); await load(); } catch (requestError) { setError(requestError.response?.data?.message || "Policy could not be deactivated."); } };
    const submitOverride = async event => { event.preventDefault(); if (!selected || !overrideReason.trim() || !overrideStatus) return; setSaving(true); setError(""); try { const response = await afterSalesService.adminOverride(selected.id, { status: overrideStatus, reason: overrideReason.trim(), customerVisible }); setSelected(response.data); setOverrideReason(""); setNotice("Admin override saved to the request timeline and audit history."); await load(); } catch (requestError) { setError(requestError.response?.data?.message || "Override could not be saved."); } finally { setSaving(false); } };

    return <main className="after-sales-admin">
        <header className="after-sales-admin-heading"><div><p>ADMINISTRATION · AFTER-SALES</p><h1>Service, returns & refunds</h1><span>Monitor every seller and customer request, manage policies, and record audited interventions.</span></div><button type="button" className="after-sales-admin-secondary" onClick={() => load()} disabled={loading}>{loading ? "Refreshing…" : "Refresh"}</button></header>
        {error && <p className="after-sales-admin-alert error">{error}</p>}{notice && <p className="after-sales-admin-alert success">{notice}</p>}
        <section className="after-sales-admin-metrics" aria-label="After-sales summary"><article><span>All requests</span><strong>{number(report.totalRequests)}</strong></article><article><span>Overdue service</span><strong>{number(report.overdue)}</strong></article><article><span>Warranty & repair</span><strong>{number((report.byType?.WARRANTY_CLAIM || 0) + (report.byType?.PAID_REPAIR || 0))}</strong></article><article><span>Returns & refunds</span><strong>{number((report.byType?.RETURN || 0) + (report.byType?.REFUND || 0))}</strong></article><article><span>Replacements</span><strong>{number(report.byType?.REPLACEMENT)}</strong></article></section>
        <section className="after-sales-admin-card"><div className="after-sales-admin-toolbar"><div className="after-sales-admin-tabs">{REQUEST_VIEWS.map(([value, name]) => <button type="button" key={value} className={activeView === value ? "active" : ""} onClick={() => setActiveView(value)}>{name}</button>)}</div><form onSubmit={applyFilters} className="after-sales-admin-filters"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Request, product, seller, invoice or serial" aria-label="Search requests" /><select value={status} onChange={event => setStatus(event.target.value)} aria-label="Request status"><option value="">All statuses</option>{STATUSES.map(value => <option key={value} value={value}>{label(value)}</option>)}</select><input type="date" value={from} onChange={event => setFrom(event.target.value)} aria-label="From date" /><input type="date" value={to} onChange={event => setTo(event.target.value)} aria-label="To date" /><button>Apply</button></form></div><div className="after-sales-admin-table-wrap"><table className="after-sales-admin-table"><thead><tr><th>Request</th><th>Product / serial</th><th>Sale reference</th><th>Seller</th><th>Type</th><th>Status</th><th>Created</th></tr></thead><tbody>{visibleRequests.map(item => <tr key={item.id} tabIndex="0" onClick={() => { setSelected(item); setOverrideStatus(item.status || ""); setOverrideReason(""); }} onKeyDown={event => event.key === "Enter" && setSelected(item)}><td><strong>{item.requestNumber}</strong><small>{item.issueCategory || "General issue"}</small></td><td><strong>{item.productName || "-"}</strong><small>{item.maskedSerial || "Non-serialised"}</small></td><td>{item.orderId ? `Order #${item.orderId}` : item.offlineBillId ? `Bill #${item.offlineBillId}` : "-"}</td><td>Seller #{item.sellerId || "-"}</td><td>{label(item.requestType)}</td><td><span className="after-sales-admin-status">{label(item.status)}</span></td><td>{date(item.requestDate)}</td></tr>)}{!loading && visibleRequests.length === 0 && <tr><td colSpan="7" className="after-sales-admin-empty">No real after-sales requests match these filters.</td></tr>}</tbody></table></div></section>
        <section className="after-sales-admin-reports after-sales-admin-card"><div><h2>Live reporting</h2><p>Counts are calculated from the selected date range and visible only to administrators.</p></div><div className="after-sales-admin-report-grid"><article><h3>By status</h3>{Object.entries(report.byStatus || {}).map(([key, value]) => <p key={key}><span>{label(key)}</span><strong>{number(value)}</strong></p>)}</article><article><h3>Seller-wise workload</h3>{Object.entries(report.sellerWise || {}).map(([key, value]) => <p key={key}><span>Seller #{key}</span><strong>{number(value)}</strong></p>)}</article></div></section>
        <section className="after-sales-admin-policy-grid"><section className="after-sales-admin-card after-sales-admin-policy-list"><div><h2>After-sales policies</h2><p>Global policy is used when no category or product policy applies.</p></div>{policies.length === 0 && <p>No policies configured.</p>}{policies.map(item => <article key={item.id}><div><strong>{item.productId ? `Product #${item.productId}` : item.categoryId ? `Category #${item.categoryId}` : "Global default"}</strong><span>{label(item.warrantyType)} · {item.warrantyMonths} months · Return {item.returnWindowDays} days</span></div><div><button type="button" onClick={() => { setEditingPolicy(item); setPolicy({ ...EMPTY_POLICY, ...item }); }}>Edit</button>{item.active && <button type="button" className="after-sales-admin-text-danger" onClick={() => deactivatePolicy(item.id)}>Deactivate</button>}</div></article>)}</section><form className="after-sales-admin-card after-sales-admin-policy-form" onSubmit={savePolicy}><h2>{editingPolicy ? "Edit policy" : "New policy"}</h2><p>Leave category/product blank to apply globally.</p><div className="after-sales-admin-field-grid">{policyField("categoryId", "Category ID")}{policyField("productId", "Product ID")}<label>Warranty type<select value={policy.warrantyType} onChange={event => setPolicy(current => ({ ...current, warrantyType: event.target.value }))}>{["MANUFACTURER", "SELLER", "EXTENDED", "NONE"].map(value => <option key={value}>{value}</option>)}</select></label>{policyField("warrantyMonths", "Warranty months")}{policyField("returnWindowDays", "Return window days")}{policyField("replacementWindowDays", "Replacement window days")}{policyField("doaWindowDays", "DOA window days")}</div><label>Required evidence<textarea value={policy.requiredEvidence || ""} onChange={event => setPolicy(current => ({ ...current, requiredEvidence: event.target.value }))} /></label><label>Policy terms<textarea value={policy.policyTerms || ""} onChange={event => setPolicy(current => ({ ...current, policyTerms: event.target.value }))} /></label><div className="after-sales-admin-checks">{[["returnable", "Returnable"], ["physicalDamageAllowed", "Physical damage allowed"], ["liquidDamageAllowed", "Liquid damage allowed"], ["openedBoxReturnAllowed", "Opened-box returns"], ["changeOfMindAllowed", "Change-of-mind returns"], ["active", "Active"]].map(([key, title]) => <label key={key}><input type="checkbox" checked={Boolean(policy[key])} onChange={event => setPolicy(current => ({ ...current, [key]: event.target.checked }))} />{title}</label>)}</div><div className="after-sales-admin-form-actions"><button disabled={saving}>{saving ? "Saving…" : "Save policy"}</button>{editingPolicy && <button type="button" className="after-sales-admin-secondary" onClick={() => { setEditingPolicy(null); setPolicy(EMPTY_POLICY); }}>Cancel</button>}</div></form></section>
        {selected && <section className="after-sales-admin-modal" role="dialog" aria-modal="true" aria-label="After-sales request detail"><article><header><div><p>{selected.requestNumber}</p><h2>{selected.productName}</h2><span>{label(selected.requestType)} · {label(selected.status)}</span></div><button type="button" className="after-sales-admin-secondary" onClick={() => setSelected(null)}>Close</button></header><div className="after-sales-admin-detail-grid"><section><h3>Customer issue</h3><p>{selected.customerIssue || "-"}</p><h3>Seller diagnosis</h3><p>{selected.sellerDiagnosis || "Pending inspection"}</p><h3>Eligibility</h3><p>Warranty: {selected.warrantyEligible ? `Eligible until ${selected.warrantyEndDate || "-"}` : "Not eligible"}</p><p>Return: {selected.returnEligible ? "Eligible" : "Not eligible"}</p>{selected.rejectionReason && <p className="after-sales-admin-rejection">Rejection: {selected.rejectionReason}</p>}</section><section><h3>Estimate / refund</h3>{selected.estimate ? <p>Estimate ₹{selected.estimate.grandTotal || 0} · {label(selected.estimate.customerApprovalStatus)}</p> : <p>No repair estimate.</p>}{selected.refunds?.length ? selected.refunds.map(refund => <p key={refund.id}>Refund ₹{refund.refundAmount} · {label(refund.refundStatus)} · {label(refund.refundMethod)}</p>) : <p>No refund recorded.</p>}<h3>Evidence</h3>{selected.attachments?.length ? <ul>{selected.attachments.map(file => <li key={file.id}>{label(file.attachmentType)} · {date(file.uploadedAt)}</li>)}</ul> : <p>No evidence uploaded.</p>}</section></div><section><h3>Status timeline</h3><ol className="after-sales-admin-timeline">{selected.history?.map((entry, index) => <li key={`${entry.changedAt}-${index}`}><strong>{label(entry.newStatus)}</strong><span>{entry.remarks || "Status updated"}</span><small>{date(entry.changedAt)} · {entry.customerVisible ? "Customer-visible" : "Internal"}</small></li>)}</ol></section><form className="after-sales-admin-override" onSubmit={submitOverride}><h3>Admin override</h3><p>This bypasses the standard seller flow only with a mandatory audit reason; every action is retained in status history.</p><select value={overrideStatus} onChange={event => setOverrideStatus(event.target.value)} required>{STATUSES.map(value => <option key={value} value={value}>{label(value)}</option>)}</select><textarea required minLength="3" maxLength="5000" value={overrideReason} onChange={event => setOverrideReason(event.target.value)} placeholder="Mandatory override reason" /><label><input type="checkbox" checked={customerVisible} onChange={event => setCustomerVisible(event.target.checked)} /> Show this remark to the customer</label><button disabled={saving}>{saving ? "Saving…" : "Record override"}</button></form></article></section>}
    </main>;
}
