import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import api from "../../services/api";
import "./AdminGrowth.css";

export default function BirthdaySettings() {
  const [form, setForm] = useState({ emailSubject: "Happy Birthday from ShivHub", messageContent: "Wishing you a wonderful birthday!", couponCode: "", bannerUrl: "", active: false }); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  useEffect(() => { api.get("/api/admin/birthday-settings").then(({ data }) => data && setForm(data)).catch(() => setError("Birthday settings could not be loaded.")); }, []);
  const save = async event => { event.preventDefault(); setError(""); try { const { data } = await api.put("/api/admin/birthday-settings", form); setForm(data); setNotice("Birthday greeting settings saved."); } catch (err) { setError(err.response?.data?.message || "Birthday settings could not be saved."); } };
  const run = async () => { setError(""); try { const { data } = await api.post("/api/admin/birthday-settings/run-now"); if (data?.status === "DISABLED") { setNotice(""); setError("Enable and save birthday greetings before running today's delivery."); return; } setNotice(`Run completed: ${data?.queued || 0} queued, ${data?.skipped || 0} skipped and ${data?.optedOut || 0} opted out from ${data?.targeted || 0} birthday customers.`); } catch (err) { setError(err.response?.data?.message || "Birthday task could not run."); } };
  return <main className="growth-page"><Link className="back-link" to="/admin/settings">← Settings</Link><header className="growth-heading"><div><p className="eyebrow">Automated greetings</p><h1>Birthday email settings</h1><p>Runs daily at 10:00 AM Asia/Kolkata for both ShivHub accounts and seller-linked customer profiles. Every attempted delivery is recorded in campaign history.</p></div></header>{error && <p className="growth-error">{error}</p>}{notice && <p className="growth-success">{notice}</p>}<form className="growth-card campaign-form" onSubmit={save}><label>Subject<input value={form.emailSubject} onChange={event => setForm(old => ({ ...old, emailSubject: event.target.value }))} required /></label><label>Email content<textarea rows="6" value={form.messageContent} onChange={event => setForm(old => ({ ...old, messageContent: event.target.value }))} required /></label><label>Optional coupon<input value={form.couponCode || ""} onChange={event => setForm(old => ({ ...old, couponCode: event.target.value }))} /></label><label>Banner URL<input value={form.bannerUrl || ""} onChange={event => setForm(old => ({ ...old, bannerUrl: event.target.value }))} /></label><label className="check-row"><input type="checkbox" checked={Boolean(form.active)} onChange={event => setForm(old => ({ ...old, active: event.target.checked }))} /> Enable automatic birthday greetings</label><div className="form-actions"><button className="primary-button">Save settings</button><button type="button" className="secondary-button" onClick={run}>Run for today</button></div></form></main>;
}
