import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { listAdminCampaigns } from "../../services/adminManagementService";
import "./AdminGrowth.css";

const date = value => value ? new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "—";

export default function CampaignManagement() {
  const [campaigns, setCampaigns] = useState([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { listAdminCampaigns().then(setCampaigns).catch(() => setError("Campaign history could not be loaded.")).finally(() => setLoading(false)); }, []);
  return <main className="growth-page"><header className="growth-heading"><div><p className="eyebrow">Customer communication</p><h1>Campaigns & Offers</h1><p>Target real customer profiles, respect consent, and audit every delivery channel.</p></div><Link className="primary-button" to="/admin/campaigns/new">+ Create campaign</Link></header><section className="metric-grid"><article><span>Total campaigns</span><strong>{campaigns.length}</strong></article><article><span>Scheduled</span><strong>{campaigns.filter(campaign => campaign.campaignStatus === "SCHEDULED").length}</strong></article><article><span>Sent delivery attempts</span><strong>{campaigns.reduce((sum, campaign) => sum + Number(campaign.sentCount || 0), 0)}</strong></article><article><span>Audience selected</span><strong>{campaigns.reduce((sum, campaign) => sum + Number(campaign.audienceCount || 0), 0)}</strong></article></section>{error && <p className="growth-error">{error}</p>}<section className="growth-card table-scroll"><table><thead><tr><th>Campaign</th><th>Message type</th><th>Channels</th><th>Audience</th><th>Status</th><th>Schedule</th><th /></tr></thead><tbody>{campaigns.map(campaign => <tr key={campaign.id}><td><strong>{campaign.title}</strong><small>{campaign.festivalName || campaign.description}</small></td><td><span className="pill neutral">{campaign.messageType || "CAMPAIGN"}</span></td><td>{campaign.channels || "IN_APP, EMAIL"}</td><td>{campaign.audienceCount || 0}</td><td><span className={`pill ${String(campaign.campaignStatus || "").toLowerCase()}`}>{campaign.campaignStatus || "DRAFT"}</span></td><td>{date(campaign.scheduledAt)}</td><td><Link className="text-button" to={`/admin/campaigns/${campaign.id}/report`}>Report & send</Link></td></tr>)}</tbody></table>{loading && <p className="empty-state">Loading campaigns…</p>}{!loading && !campaigns.length && <p className="empty-state">Create the first festival, offer, reminder, or announcement campaign.</p>}</section></main>;
}
