import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getAdminCampaignReport, retryFailedAdminCampaign, sendAdminCampaign, testAdminCampaign } from "../../services/adminManagementService";
import "./AdminGrowth.css";

const date = value => value ? new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "—";

export default function CampaignReport() {
  const { id } = useParams(); const [report, setReport] = useState(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [testEmail, setTestEmail] = useState(""); const [notice, setNotice] = useState(""); const [status, setStatus] = useState(""); const [query, setQuery] = useState("");
  const load = useCallback(() => getAdminCampaignReport(id, { status: status || undefined, query: query || undefined }).then(setReport).catch(() => setError("Campaign report could not be loaded.")), [id, status, query]);
  useEffect(() => { load(); }, [load]);
  const send = async () => { if (!window.confirm("Queue this campaign for delivery?")) return; setBusy(true); try { const result = await sendAdminCampaign(id); setNotice(`${result.queued || 0} email(s) queued. Sent/failed counts update as SMTP attempts finish.`); load(); } catch (err) { setError(err.response?.data?.message || "Campaign could not be queued."); } finally { setBusy(false); } };
  const retry = async () => { setBusy(true); try { const result = await retryFailedAdminCampaign(id); setNotice(`${result.queued || 0} failed email(s) queued for retry.`); load(); } catch { setError("Failed deliveries could not be queued for retry."); } finally { setBusy(false); } };
  const test = async event => { event.preventDefault(); if (!testEmail) return; setBusy(true); try { const result = await testAdminCampaign(id, testEmail); setNotice(result.message); load(); } catch (err) { setError(err.response?.data?.message || "Test message could not be queued."); } finally { setBusy(false); } };
  if (!report && !error) return <main className="growth-page"><p>Loading campaign report…</p></main>;
  const campaign = report?.campaign;
  return <main className="growth-page"><Link className="back-link" to="/admin/campaigns">← Campaigns</Link>{error && <p className="growth-error">{error}</p>}{notice && <p className="growth-success">{notice}</p>}{campaign && <><header className="growth-heading"><div><p className="eyebrow">Campaign report</p><h1>{campaign.title}</h1><p>{campaign.messageType} · Email · {campaign.campaignStatus}</p></div><div className="form-actions"><button className="secondary-button" disabled={busy || !report.failed} onClick={retry}>Retry failed ({report.failed || 0})</button><button className="primary-button" disabled={busy} onClick={send}>{busy ? "Working…" : "Queue campaign"}</button></div></header><section className="metric-grid"><article><span>Targeted</span><strong>{report.targeted || 0}</strong></article><article><span>Queued</span><strong>{report.queued || 0}</strong></article><article><span>Sent</span><strong>{report.sent || 0}</strong></article><article><span>Failed / opted out</span><strong>{report.failed || 0} / {report.optedOut || 0}</strong></article></section><section className="detail-columns"><form className="growth-card test-form" onSubmit={test}><h2>Send test email</h2><p>Only the entered address is queued; customer recipients are not used.</p><input type="email" value={testEmail} onChange={event => setTestEmail(event.target.value)} placeholder="you@example.com" required /><button className="secondary-button" disabled={busy}>Queue test</button></form><section className="growth-card"><h2>Delivery filters</h2><select value={status} onChange={event => setStatus(event.target.value)}><option value="">All statuses</option><option>PENDING</option><option>SENT</option><option>FAILED</option><option>SKIPPED</option><option>OPTED_OUT</option></select><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search recipient" /><button className="secondary-button" type="button" onClick={load}>Search</button></section></section><section className="growth-card table-scroll"><h2>Delivery history</h2><table><thead><tr><th>Recipient</th><th>Status</th><th>Failure reason</th><th>Queued / sent</th></tr></thead><tbody>{report.history?.map(delivery => <tr key={delivery.id}><td>{delivery.recipientName || delivery.recipientEmail}<small>{delivery.recipientEmail}</small></td><td><span className={`pill ${String(delivery.status || "").toLowerCase()}`}>{delivery.status}</span></td><td>{delivery.failureReason || delivery.message || "—"}</td><td>{date(delivery.sentAt || delivery.createdAt)}</td></tr>)}</tbody></table>{!report.history?.length && <p className="empty-state">No delivery attempts match these filters.</p>}</section></>}</main>;
}
