import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { approveSeller, getSeller, rejectSeller } from "../../services/adminService";
import "./AdminManagement.css";
export default function SellerDetails() {
 const {id}=useParams(), navigate=useNavigate(); const [seller,setSeller]=useState(null),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{getSeller(id).then(setSeller).catch(()=>setError("Seller details could not be loaded."));},[id]);
 const decide=async(action)=>{if(action==="reject"&&!reason.trim()){setError("Enter a rejection reason before sending the decision.");return;}setBusy(true);setError("");try{await (action==="approve"?approveSeller(id):rejectSeller(id,reason));navigate("/admin/seller-requests");}catch(e){setError(e.response?.data?.message||"The decision could not be saved.");}finally{setBusy(false);}};
 if(!seller&&!error)return <section className="admin-management"><p>Loading seller…</p></section>;
 return <section className="admin-management"><Link className="back-link" to="/admin/seller-requests">← Seller requests</Link>{error&&<p className="admin-error">{error}</p>}{seller&&<><header><div><p className="eyebrow">Seller application</p><h1>{seller.name}</h1><p>Seller #{seller.id} · <span className={`status ${seller.status?.toLowerCase()}`}>{seller.status}</span></p></div></header><div className="detail-grid"><article className="management-card"><h2>Contact details</h2><dl><dt>Email</dt><dd>{seller.email}</dd><dt>Mobile</dt><dd>{seller.mobile||"Not provided"}</dd></dl></article>{seller.status==="PENDING"&&<article className="management-card review-card"><h2>Decision</h2><p>Approval sends an account-ready email. Rejection requires a reason and emails it to the applicant.</p><label>Rejection reason<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain what the applicant needs to change…" /></label><div className="decision-actions"><button disabled={busy} className="approve" onClick={()=>decide("approve")}>Approve & email</button><button disabled={busy} className="reject" onClick={()=>decide("reject")}>Reject & email</button></div></article>}</div>{seller.rejectionReason&&<article className="management-card"><h2>Rejection reason</h2><p>{seller.rejectionReason}</p></article>}</>}</section>;
}
