import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import api from "../../services/api";
import "./AdminTools.css";
import "../seller/AddOtherProduct.css";

const blank = { specificationKey: "", displayLabel: "", inputType: "TEXT", optionsJson: "", requiredField: false, filterable: false, variantEnabled: false, displayOrder: 0, active: true };
export default function SubcategoryFields() {
    const [categories, setCategories] = useState([]), [subcategories, setSubcategories] = useState([]), [fields, setFields] = useState([]);
    const [categoryId, setCategoryId] = useState(""), [subCategoryId, setSubCategoryId] = useState(""), [form, setForm] = useState(blank), [error, setError] = useState(""), [saving, setSaving] = useState(false);
    const load = async () => { const { data } = await api.get("/api/admin/product-specification-templates"); setFields(data); };
    useEffect(() => { let active=true; Promise.all([api.get("/api/categories"), api.get("/api/admin/product-specification-templates")]).then(([cats, templates]) => { if(active){setCategories(cats.data.filter(c => c.name.toLowerCase() !== "mobiles"));setFields(templates.data);} }).catch(e => {if(active)setError(e.response?.data?.message || "Unable to load fields.");});return()=>{active=false;}; }, []);
    useEffect(() => { let active=true;setSubcategories([]);if(categoryId)api.get(`/api/categories/${categoryId}/subcategories`).then(({data})=>{if(active)setSubcategories(data);}).catch(e=>{if(active)setError(e.response?.data?.message||"Unable to load subcategories.");});return()=>{active=false;}; }, [categoryId]);
    const change = (key, value) => setForm(current => ({ ...current, [key]: value }));
    const save = async event => {event.preventDefault();setSaving(true);setError("");try {const payload={...form,categoryId:Number(categoryId),subCategoryId:Number(subCategoryId),displayOrder:Number(form.displayOrder)};await api[form.id?"put":"post"](`/api/admin/product-specification-templates${form.id?`/${form.id}`:""}`,payload);setForm(blank);await load();}catch(e){setError(e.response?.data?.message||"Field could not be saved.");}finally{setSaving(false);}};
    const deactivate = async field => {try{await api.delete(`/api/admin/product-specification-templates/${field.id}`);await load();}catch(e){setError(e.response?.data?.message||"Could not deactivate field.");}};
    const selected = fields.filter(field=>String(field.categoryId)===categoryId&&(field.subCategoryId===null||String(field.subCategoryId)===subCategoryId));
    return <main className="admin-tools add-other-product"><header><div><p className="eyebrow">CATALOGUE CONFIGURATION</p><h1>Subcategory Fields</h1><p>Configure non-mobile details and variant axes. The separate Mobile module is protected.</p></div><Link to="/admin/dashboard">Dashboard</Link></header>{error&&<p role="alert" className="error">{error}</p>}
        <section className="add-other-grid"><label>Category<select value={categoryId} onChange={e=>{setCategoryId(e.target.value);setSubCategoryId("");setForm(blank);}}><option value="">Select category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Subcategory<select value={subCategoryId} disabled={!categoryId} onChange={e=>{setSubCategoryId(e.target.value);setForm(blank);}}><option value="">Select subcategory</option>{subcategories.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></section>
        {subCategoryId&&<><form onSubmit={save}><section><h2>{form.id?"Edit field":"Add field"}</h2><div className="add-other-grid"><label>Key<input required disabled={!!form.id} value={form.specificationKey} maxLength={80} onChange={e=>change("specificationKey",e.target.value)} /></label><label>Display name<input required value={form.displayLabel} maxLength={120} onChange={e=>change("displayLabel",e.target.value)} /></label><label>Input type<select value={form.inputType} onChange={e=>change("inputType",e.target.value)}>{["TEXT","NUMBER","SELECT","MULTI_SELECT","BOOLEAN","TEXTAREA"].map(t=><option key={t}>{t}</option>)}</select></label><label>Options (JSON array or comma-separated)<textarea value={form.optionsJson||""} required={["SELECT","MULTI_SELECT"].includes(form.inputType)} onChange={e=>change("optionsJson",e.target.value)} /></label><label>Display order<input type="number" min="0" value={form.displayOrder} onChange={e=>change("displayOrder",e.target.value)} /></label>{[["requiredField","Required"],["filterable","Customer filter"],["variantEnabled","Variant axis"],["active","Active"]].map(([key,label])=><label className="checkbox" key={key}><input type="checkbox" checked={form[key]} onChange={e=>change(key,e.target.checked)} />{label}</label>)}</div><button disabled={saving}>{saving?"Saving…":"Save field"}</button>{form.id&&<button type="button" onClick={()=>setForm(blank)}>Cancel edit</button>}</section></form>
        <section><h2>Configured fields</h2><p>Variant axes require one value per combination. Deactivation preserves saved product/order details.</p><table><thead><tr><th>Order</th><th>Field</th><th>Type</th><th>Variant</th><th>Status</th><th>Actions</th></tr></thead><tbody>{selected.map(f=><tr key={f.id}><td>{f.displayOrder}</td><td>{f.displayLabel}{f.requiredField?" *":""}</td><td>{f.inputType}</td><td>{f.variantEnabled?"Yes":"No"}</td><td>{f.active?"Active":"Inactive"}</td><td><button type="button" onClick={()=>setForm(f)}>Edit</button>{f.active&&<button type="button" onClick={()=>deactivate(f)}>Deactivate</button>}</td></tr>)}</tbody></table></section></>}
    </main>;
}
